.readthedocs.yml
docs/en/api/utils.rst
docs/zh_cn/api/utils.rst
requirements/docs.txt

https://mmengine-test.readthedocs.io/en/latest/
https://mmengine-test-zh-cn.readthedocs.io/ …

[Docs] Add readthedocs.yml

---

docs/zh_cn/tutorials/runner.md

[Fix] max_epoch to max_iters

---

README.md

[Doc] Polish the readme

---

mmengine/version.py

[Fix] Bump version to 0.1.0

---

README_zh-CN.md
docs/zh_cn/get_started/introduction.md

[Fix] MacOS to macOS

---

docker/README.md
docker/dev/Dockerfile
docker/release/Dockerfile

Add dockerfile

---

mmengine/model/wrappers/fully_sharded_distributed.py

Correct sequence:
Miss sharding strategy: …

[Fix] Fix error argument sequence in fsdp.

---

mmengine/model/averaged_model.py

Use torch.lerp_() to speed up EMA.
replace 
```python
averaged_param.mul_(1 - momentum).add_(source_param, alpha=momentum)
```
with
```python
averaged_param.lerp_(source_param, momentum)
```
None
3. If the modification has …

[Enhance] Use torch.lerp_() to speed up EMA.

---

mmengine/hooks/ema_hook.py
tests/test_hooks/test_ema_hook.py

Resolving circular import caused by #507  …

[Fix] Fix circle import in EMAHook

---

docs/en/api/dataset.rst
docs/en/api/device.rst
docs/en/api/dist.rst
docs/en/api/evaluator.rst
docs/en/api/fileio.rst
docs/en/api/hub.rst
docs/en/api/logging.rst
docs/en/api/model.rst
docs/en/api/optim.rst
docs/en/api/registry.rst
docs/en/api/runner.rst
docs/en/api/utils.dl_utils.rst
docs/en/api/utils.rst
docs/zh_cn/api/hub.rst

Expected rendered docs:
But got:
Replace all api files in en docs with zh_cn.
No
4. …

[Docs] Fix api files of en docs

---

mmengine/structures/instance_data.py

fix typo in `instance_data.py`.

[Docs] Fix typo in `instance_data.py`

---

.github/workflows/merge_stage_test.yml
mmengine/testing/_internal/distributed.py

1. Fix merge workflow(skip some unit tests in windows).
2. Change timeout of `MultiProcessTestCase` from 500 to 1000, since multiprocessing unit test in windows could not be completed 500s. …

[Fix] Fix merge ci & multiprocessing unit test

---

mmengine/registry/registry.py

Remove unnecessary "if statement".

Remove unnecessary "if statement"

---

mmengine/runner/runner.py

[Fix] Support compare numpy array dataset meta

---

README.md
README_zh-CN.md

Revise documents
README.md
README_zh-CN.md
4. The documentation has been modified accordingly, like …

revise docs

---

mmengine/model/wrappers/distributed.py
tests/test_model/test_wrappers/test_model_wrapper.py

Solve #574
2. The modification …

[Fix] Fix detect_anomalous_params

---

mmengine/model/wrappers/test_time_aug.py

[Fix] Fix base tta model

---

docs/zh_cn/tutorials/model.md

[Docs] Fix typo in docs/zh_cn/tutorials/model.md

---

docs/zh_cn/tutorials/config.md

[Docs] Fix typo in docs/zh_cn/tutorials/config.md

---

CODEOWNERS

Add `CODEOWNERS` file for auto assigning reviewer.
1. Pre-commit or other linting …

[Enhancement] Add `CODEOWNERS` file for auto assigning reviewer

---

.owners.yml

Add issue or pr assignees

---

.github/workflows/merge_stage_test.yml
.github/workflows/pr_stage_test.yml

[Fix] Fix pip upgrade CI

---

README.md
README_zh-CN.md

[Docs] Add mmyolo link in README

---

docs/en/api/utils.rst
docs/zh_cn/api/utils.rst
mmengine/utils/misc.py
tests/test_utils/test_misc.py

Add a function to mark the deprecated function (copied from https://github.com/pytorch/pytorch/blob/master/torch/onnx/_deprecation.py).
If this PR introduces a new feature, it is better to list some use cases here, and …

[Enhancement] Add a function to mark the deprecated function.

---

mmengine/model/wrappers/utils.py

[Fix] Fix error implementation of `is_model_wrapper`

---

docs/zh_cn/advanced_tutorials/data_element.md
docs/zh_cn/design/hook.md

[Docs] Fix typo

---

mmengine/config/config.py

[Fix] Fix open() encoding problem of Config in Windows

---

mmengine/model/averaged_model.py
tests/test_model/test_averaged_model.py

Add docstring and warning to avoid incorrect momentum of EMA.
Refine docstring and add a warning.

[Enhance] Raise warning for abnormal momentum.

---

mmengine/config/config.py

I found the missing '.'
2. The …

fix config .

---

mmengine/dataset/base_dataset.py

[Docs] Fix docstring of BaseDataset

---

README.md
README_zh-CN.md
docs/en/notes/changelog.md
mmengine/version.py

Bump version to v0.3.0

---

README.md
README_zh-CN.md

fix MMEval in README

---

mmengine/runner/log_processor.py
mmengine/runner/runner.py

[Fix]Fix error URL in runner docstring

---

mmengine/config/utils.py

[Fix] Add mmyolo to PKG2PROJECT

---

mmengine/config/config.py
mmengine/optim/scheduler/param_scheduler.py
mmengine/registry/utils.py

Replace `print` with `print_log` for those function called by runner.
1. Pre-commit or other linting tools are …

[Enhance] Replace `print` with `print_log` for those function called by runner

---

docs/zh_cn/tutorials/hook.md

[Docs] Refine hook doc

---

docs/en/advanced_tutorials/cross_library.md

[Doc] Add cross library en doc.

---

docs/zh_cn/tutorials/param_scheduler.md

[Doc] Update scheduler doc.

---

docs/en/advanced_tutorials/distributed.md
docs/zh_cn/advanced_tutorials/distributed.md

[Docs] Translate distributed communication

---

docs/en/tutorials/hook.md

[Docs] Translate hook docs

---

docs/en/advanced_tutorials/logging.md
docs/zh_cn/advanced_tutorials/logging.md

[Docs] Translate the logging

---

mmengine/runner/checkpoint.py

Original format: `local loads checkpoint from path xxxx`, and this will be logged multiple times in ddp training.
New format: `Loads checkpoint by locals backend from xxxx`, and will be formatted by `MMLogger`.
If this PR …

[Enhance] Format the log of `CheckpointLoader.load_checkpoint`

---

docs/en/_static/css/readthedocs.css
docs/zh_cn/_static/css/readthedocs.css

Using `two-column-table-wrapper` like this:
```markdown
<table class="docutils">
<thead>
<tr>
<th>Model in MMCV</th>
<th>Model in MMEngine</th>
<tbody>
<tr>
<td valign="top" class='two-column-table-wrapper'><div style="overflow-x: auto">
...
</div>
</td>
<td valign="top" class='two-column-table-wrapper'><div style="overflow-x: auto">
...
</td>
</div>
</tr>
</thead>
</table>
```
`<td valign="top" class='two-column-table-wrapper'><div style="overflow-x: auto">` makes each cell in table scrollable:
Please briefly describe what …

[Docs] Update two-column table wrapper

---

docs/en/migration/param_scheduler.md

[Doc] Translate scheduler migration

---

mmengine/evaluator/evaluator.py
mmengine/model/averaged_model.py
tests/test_evaluator/test_evaluator.py
tests/test_model/test_averaged_model.py

[Enhance] Raise warning for abnormal momentum (#655)
[Fix] Fix offline_evaluate index error (#630)

Cherry pick dev

---

docs/en/advanced_tutorials/visualization.md
docs/en/design/visualization.md
docs/zh_cn/advanced_tutorials/visualization.md

Translate visualization documents
modified:   docs/en/advanced_tutorials/visualization.md
modified:   docs/en/design/visualization.md
modified:   docs/zh_cn/advanced_tutorials/visualization.md
modified:   docs/zh_cn/design/visualization.md
3. …

[Docs] Visualization docs translate

---

mmengine/utils/version_utils.py

Fix https://github.com/open-mmlab/mmengine/issues/714
@HAOCHENYE  Hi, apologies, not sure what happened, but https://github.com/open-mmlab/mmengine/pull/717 changes disappeared. I'm not sure if a bot force pushed my commit out?
send stderr to subprocess.PIPE
3. If the modification has potential influence on downstream projects, this PR …

send stderr to subprocess.PIPE

---

docs/en/examples/resume_training.md
docs/en/examples/speed_up_training.md
docs/zh_cn/examples/speed_up_training.md

[Docs] Translate examples docs

---

docs/en/advanced_tutorials/manager_mixin.md
docs/en/advanced_tutorials/utils.md
docs/en/index.rst
docs/zh_cn/advanced_tutorials/manager_mixin.md
docs/zh_cn/index.rst

[Docs] translate the mangermixin tutorial

---

docs/en/tutorials/dataset.md

[Docs] Translate dataset tutorial

---

mmengine/optim/scheduler/param_scheduler.py

As T_max could be None, so we need to check its value.
Add value check of T-max in CosineAnnealingParamScheduler …

[Fix] Fix bug of CosineAnnealingParamScheduler

---

.pre-commit-config-zh-cn.yaml

Prevent pre-commit jamming in domestic operation.
Correct repo in pre-commit.

[Fix] Fix .pre-commit-config-zh-cn.yaml pyupgrade-repo github->gitee

---

docs/en/design/logging.md
docs/zh_cn/design/logging.md

[Docs] translate logging design

---

docs/en/advanced_tutorials/fileio.md
docs/zh_cn/advanced_tutorials/fileio.md

Translate the fileio tutorials doc.
- docs/en/advanced_tutorials/fileio.md
- docs/zh_cn/advanced_tutorials/fileio.md

[Docs] Translate fileio doc

---

docs/en/advanced_tutorials/config.md

[Docs] Translate the config tutorial

---

docs/en/tutorials/runner.md
docs/zh_cn/tutorials/runner.md

[Docs] Translate runner tutorial

---

docs/en/tutorials/model.md
docs/zh_cn/tutorials/model.md

[Docs] Translate model tutorial

---

mmengine/fileio/backends/petrel_backend.py
tests/test_fileio/test_backends/test_petrel_backend.py
tests/test_fileio/test_fileclient.py

Add conf_path in PetrelBackend initial parameters to set user-defined petrel client config path.
Add conf_path in PetrelBackend initial parameters to set user-defined petrel client config path.
If this PR introduces a new feature, it is better to list some use cases here, and update …

feat: add conf_path in PetrelBackend

---

docs/en/_static/css/readthedocs.css
docs/en/migration/model.md
docs/zh_cn/_static/css/readthedocs.css
docs/zh_cn/migration/model.md

[Docs] Translate migrate model

---

docs/en/tutorials/param_scheduler.md

[Docs] Scheduler doc EN version.

---

docs/en/get_started/15_minutes.md
docs/zh_cn/get_started/15_minutes.md

[Docs] Add gif to 15 min tutorial

---

docs/en/notes/contributing.md

Fix typos in EN `contributing.md` according to https://github.com/open-mmlab/mmcv/pull/2462.

[Doc] fix typos in EN `contributing.md`

---

docs/en/advanced_tutorials/logging.md
docs/zh_cn/advanced_tutorials/logging.md

[Docs] Replace markdown table with html table

---

mmengine/visualization/visualizer.py

Examples are out of data, so update. 
According to the latest 'Visualizer.draw_polygons',  fix them.

Visualizer.draw_polygons examples wrong

---

mmengine/hooks/hook.py
tests/test_hooks/test_hook.py

[Refactor] Refactor unit test of Base hook

---

tests/test_hooks/test_empty_cache_hook.py

[Refactor] Refactor unit test of empty cache hook

---

docs/en/tutorials/hook.md
docs/en/tutorials/model.md
docs/en/tutorials/param_scheduler.md
docs/zh_cn/tutorials/evaluation.md

[Docs] Fix typos 

---

docs/en/advanced_tutorials/basedataset.md
docs/en/advanced_tutorials/config.md
docs/en/advanced_tutorials/registry.md
docs/en/tutorials/param_scheduler.md

Fix wrong links and typos in doc …

[Docs] Fix wrong links and typos in doc

---

docs/en/design/hook.md
docs/zh_cn/design/hook.md

[Docs] Translate the documentation of hook design

---

mmengine/optim/optimizer/default_constructor.py
mmengine/visualization/vis_backend.py

[Docs] Fix docstring format

---

tests/test_utils/test_timer.py

The unit test of the `Timer` could failed in Windows or macOS platforms.
1. Pre-commit or other linting tools …

[Fix] only test timer in linux

---

.github/ISSUE_TEMPLATE/3-documentation.yml

2. The modification is covered …

[Docs] Update docs issue template

---

mmengine/structures/base_data_element.py
mmengine/structures/instance_data.py
mmengine/structures/label_data.py
mmengine/structures/pixel_data.py
tests/test_structures/test_instance_data.py

Update docstring of `structures`

---

tests/test_hooks/test_iter_timer_hook.py

[Refactor] Refactor itertimer hook unittest

---

tests/test_hooks/test_runtime_info_hook.py

[Refactor] Refactor unittest of `RuntimeInfohook`

---

docs/en/advanced_tutorials/initialize.md

[Fix] link error in initialize tutorial.

---

docs/en/advanced_tutorials/initialize.md
docs/zh_cn/advanced_tutorials/initialize.md

[Docs] Fix table in initialized.md

---

tests/test_hooks/test_param_scheduler_hook.py

[Refactor] Refactor unit test of ParamSchedulerHook

---

mmengine/infer/infer.py
tests/test_infer/test_infer.py

Enables loading alias as a string or an array.

[Enhance] Dynamic alias type in Inference

---

docs/en/advanced_tutorials/logging.md
docs/zh_cn/advanced_tutorials/logging.md

Fix typos in `advanced_tutorials/logging.md`

[Docs] Fix typos in `advanced_tutorials/logging.md`

---

docs/en/get_started/installation.md
docs/zh_cn/get_started/installation.md
mmengine/logging/logger.py

[Docs] Clear the documentations about Python3.6

---

mmengine/infer/infer.py
tests/test_infer/test_infer.py

Since MMEngine will save the config in the checkpoint, inferencer could be able to load the config from the checkpoint and inference without giving a config.
If this PR introduces a new feature, it is better to list some …

[Enhance] Support load config from checkpoint.

---

docs/en/advanced_tutorials/fileio.md
docs/zh_cn/advanced_tutorials/fileio.md

[Docs] Update `fileio.md`

---

examples/distributed_training.py
mmengine/config/utils.py
mmengine/registry/registry.py

The package name of MMAction should be `mmaction` rather than `mmaction2`
1. Pre-commit or other linting tools …

[Fix] Fix error package name defined in `PKG2PROJECT`

---

README.md
README_zh-CN.md
docs/en/notes/changelog.md
mmengine/version.py

Bump version to v0.5.0

---

.pre-commit-config-zh-cn.yaml
.pre-commit-config.yaml

Use official isort.
Link https://github.com/open-mmlab/mmeval/pull/86

Use official isort

---

mmengine/logging/message_hub.py
tests/test_logging/test_message_hub.py

[Fix] Support update `np.ScalarType` data in message_hub

---

mmengine/visualization/visualizer.py

…rder to show Chinese characters.
solve issue [882](https://github.com/open-mmlab/mmengine/issues/882)
1. …

[Feature] visualizer.draw_texts() adds a font_properties argument

---

docs/en/advanced_tutorials/visualization.md
docs/en/notes/changelog.md
docs/zh_cn/advanced_tutorials/visualization.md
docs/zh_cn/notes/changelog.md

[Docs] Refine the format of changelog and visualization document

---

.github/ISSUE_TEMPLATE/1-bug-report.yml
.github/ISSUE_TEMPLATE/2-feature_request.yml
.github/ISSUE_TEMPLATE/3-documentation.yml

Update the links in the issue templates

---

mmengine/fileio/file_client.py
mmengine/fileio/io.py
mmengine/hooks/logger_hook.py
mmengine/hooks/naive_visualization_hook.py
mmengine/optim/optimizer/default_constructor.py
mmengine/optim/optimizer/optimizer_wrapper.py
mmengine/optim/scheduler/lr_scheduler.py
mmengine/optim/scheduler/momentum_scheduler.py
mmengine/optim/scheduler/param_scheduler.py
mmengine/registry/registry.py
mmengine/registry/utils.py
mmengine/runner/checkpoint.py
mmengine/runner/runner.py
mmengine/runner/utils.py
mmengine/utils/dl_utils/hub.py
mmengine/utils/misc.py
mmengine/utils/path.py
mmengine/utils/version_utils.py
mmengine/visualization/vis_backend.py
mmengine/visualization/visualizer.py

Fix docstring

---

docs/en/api/runner.rst
docs/zh_cn/api/runner.rst
docs/zh_cn/common_usage/set_random_seed.md
docs/zh_cn/index.rst

[Docs] Introduce how to set random seed

---

mmengine/runner/runner.py
tests/test_registry/test_build_functions.py
tests/test_runner/test_runner.py

change `shedule` to `schedule`.

[Docs] Fix typo `shedule`

---

docs/en/advanced_tutorials/model_analysis.md
mmengine/analysis/complexity_analysis.py
mmengine/analysis/print_helper.py

Refine the style of table

---

mmengine/registry/build_functions.py
mmengine/registry/root.py

Fix failed URL

---

mmengine/dist/dist.py

This is linked to “To avoid tensor contiguity problems in distributed training #879”

[Enhance] Make sure Tensors to broadcast is contiguous

---

CODEOWNERS

Change CODEOWNER

---

docs/en/tutorials/optim_wrapper.md
docs/zh_cn/tutorials/optim_wrapper.md
mmengine/optim/optimizer/builder.py
requirements/tests.txt
tests/test_optim/test_optimizer/test_optimizer.py

Add `Lion` optimizer from https://github.com/lucidrains/lion-pytorch
No
```python
optim_wrapper = dict(
type='OptimWrapper',
optimizer=dict(type='Lion', lr=1e-4)
)
```
3. If the modification has potential influence on downstream projects, this PR should be tested with …

[Feature] Add Lion optimizer

---

docs/en/common_usage/debug_tricks.md

Translate "Debug Tricks" to English
Translate "Debug Tricks" to English …

[Docs] Translate "Debug Tricks" to English

---

tests/test_optim/test_optimizer/test_optimizer_wrapper.py

[Fix] fix optim_wrapper unittest for pytorch < 1.10.0

---

docs/en/tutorials/hook.md
docs/zh_cn/tutorials/hook.md

fix type error in custom_hooks doc.
update en and zh_cn hooks doc.

[Docs] Fix typo in hook document

---

docs/en/advanced_tutorials/registry.md
docs/en/tutorials/dataset.md
docs/zh_cn/advanced_tutorials/registry.md
docs/zh_cn/tutorials/dataset.md
mmengine/dataset/utils.py
mmengine/infer/infer.py
mmengine/registry/__init__.py
mmengine/registry/root.py
mmengine/runner/runner.py
tests/test_hooks/test_logger_hook.py
tests/test_runner/test_runner.py

1. Add `FUNCTIONS` registry
2. Make `COLLATE_FUNCTION` as an alias of `FUNCTIONS`
3. Update docs
1. Pre-commit …

[Enhancement] Add `FUNCTIONS` root Registry

---

docs/en/notes/changelog.md

[Fix] Fix changelog date

---

mmengine/logging/logger.py
tests/test_logging/test_logger.py

`MMLogger.warning` will not filter the repeated warning, therefore the training message could be fully filled with the signs.
If this PR introduces a new feature, it is better to list some use cases here, and update the …

[Fix] Fix repeated warning

---

CITATION.cff
README.md
README_zh-CN.md

Add citation in README

---

mmengine/config/utils.py

The `mmpretrain` package will release recently. Please add it to the pre-deifined module names.

[Enhance] Add `mmpretrain` to the `MODULE2PACKAGE`.

---

README.md
README_zh-CN.md

[Docs] Add more social networking links

---

mmengine/runner/runner.py

[Enhancement] Do not print config if it is empty

---

mmengine/registry/registry.py

Suppress registry warning like: …

[Enhance] Suppress registry warning

---

mmengine/runner/runner.py

[Enhance] Remove useless variable declaration

---

docs/en/tutorials/evaluation.md
docs/zh_cn/design/evaluation.md
docs/zh_cn/tutorials/evaluation.md

[Docs] Translate tutorials/evaluation.md

---

mmengine/dist/dist.py
mmengine/evaluator/metric.py
tests/test_evaluator/test_metric.py

BaseMetric will synchronize data from different ranks to local directory `.dist`. However this cause error in some cases:
1. local directory do not have enough space to store the data.
2. In multi-node training, the local directory may not be shared storage, which means `.dist` will be saved on different nodes.
If so, please describe how it breaks the compatibility …

[Enhance] Support configuring synchronize directory for BaseMetric

---

mmengine/runner/log_processor.py
tests/test_runner/test_log_processor.py

[Fix] when `log_with_hierarchy` is `True`, the running error appears in `_collect_scalars` for log processor

---

.github/workflows/merge_stage_test.yml
.github/workflows/pr_stage_test.yml

The image of Ubuntu 22.04 can lead to some strange errors, so it is necessary to install and update the wheel. …

[Fix] Fix merge ci

---

docs/en/common_usage/speed_up_training.md
docs/zh_cn/common_usage/speed_up_training.md
mmengine/optim/optimizer/builder.py

Add npu optimizer.
mmengine/optim/optimizer/builder.py.
None.
python tools/train.py configs/resnet/resnet50_8xb32_in1k.py --cfg-options optimizer.type=NpuFusedSGD.
3. If the modification has potential influence on downstream projects, …

[Feature] Add torch_npu optimizer

---

mmengine/logging/message_hub.py

1. Fix examples in docstring.
2. Enhance error catching in `MessageHub`
1. Pre-commit or other linting tools are …

[Enhance] Enhance docstring and error cathing in `MessageHub` 

---

mmengine/runner/runner.py
tests/test_runner/test_runner.py

2. The modification is covered …

[Fix] collate_fn does not support passing a function object

---

mmengine/runner/checkpoint.py
tests/test_runner/test_checkpoint.py

The original `load_state_dict` doesn't support PyTorch-style `_load_state_dict_post_hooks`.
Add supports.
No

[Imporve] Support `_load_state_dict_post_hooks` in `load_state_dict`.

---

examples/text_classification.py

Inspired by #1117 , I create a text classification example with mmengine and transformers kit(I think transformers kit has been the essential tools for nlp research).
Using the [imdb](https://huggingface.co/datasets/imdb) dataset to fine-tune the pretrained model [bert-base-uncased](https://huggingface.co/bert-base-uncased).

[Enhancement] Creating a text classification example.

---

mmengine/infer/infer.py

Provide solutions for issue #1112  solving.
Added a bool parameter 'show_progress' to the 'BaseInference' class to control whether to show the progress bar, default is 'True', show the progress bar.

[Enhancement] Add an option to control whether to show progress bar in BaseInference	

---

mmengine/model/base_model/base_model.py

Corrected comment error

---

mmengine/optim/scheduler/param_scheduler.py
mmengine/visualization/vis_backend.py

fix format

---

examples/distributed_training.py
mmengine/testing/_internal/distributed.py

Fix unit test error due to program abort caused by limited resources

---

mmengine/hooks/checkpoint_hook.py
tests/test_hooks/test_checkpoint_hook.py

[Refactor] Let unit tests not affect each other

---

docs/en/common_usage/distributed_training.md
docs/en/common_usage/speed_up_training.md
docs/en/index.rst
docs/zh_cn/common_usage/distributed_training.md
docs/zh_cn/common_usage/speed_up_training.md
docs/zh_cn/index.rst

[Docs] Move the usage of distributed training to a single document

---

mmengine/logging/logger.py

When using downstream framework such as `mmdet3d` to train models with following script:
```bash
bash tools/dist_train.sh ${CONFIG_FILE} ${GPU_NUM}
```
It will cause an `AttributeError` that:
```
'int' object has no attribute 'isdigit'
```
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep …

[Fix] logger error

---

docs/en/common_usage/visualize_training_log.md
docs/zh_cn/common_usage/visualize_training_log.md

[Docs] Add the usage of clearml

---

mmengine/visualization/vis_backend.py

support wandb resume
support wandb resume
If this PR introduces a new feature, it is better to list some use cases here, and …

[Enhance] WandbVisBackend supports updating config

---

mmengine/hooks/checkpoint_hook.py

[Fix] CheckpointHook should check whether file exists before removing it

---

docs/en/migration/param_scheduler.md
docs/zh_cn/migration/param_scheduler.md

There are some parameter typing error in document, when user just copy the code, the code not work. 
Fix parameter typing error in document.
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility …

Fix parameter typing error in document.

---

.circleci/test.yml
.github/workflows/merge_stage_test.yml
.github/workflows/pr_stage_test.yml

Skip mmcv in CI when torch < 1.8

---

.github/workflows/merge_stage_test.yml

Fix the syntax in github action

---

docs/en/tutorials/runner.md

Small fix of an error in the doc.

[Docs] Fix a comment in runner tutorial

---

docs/zh_cn/index.rst
docs/zh_cn/notes/debug_with_vscode.md

[Docs] Add a document to introduce how to debug with vscode

---

mmengine/runner/runner.py

[Fix] Fix undefined variable error in Runner

---

docs/zh_cn/advanced_tutorials/config.md

[Docs] Fix config doc

---

.github/workflows/pr_stage_test.yml
mmengine/_strategy/base.py
mmengine/_strategy/fsdp.py
tests/test_model/test_wrappers/test_model_wrapper.py

Fix docstring format

---

mmengine/config/config.py
mmengine/runner/_flexible_runner.py
tests/test_config/test_config.py

[Enhance] Config adds copy method

---

README.md
README_zh-CN.md
docs/en/notes/changelog.md
mmengine/version.py

Bump version to v0.8.0

---

mmengine/config/config.py
mmengine/model/wrappers/fully_sharded_distributed.py
tests/data/config/lazy_module_config/toy_model.py
tests/test_config/test_config.py

[Fix] Implement `copy` and `__copy__` for `ConfigDict`

---

mmengine/model/wrappers/fully_sharded_distributed.py
tests/test_model/test_wrappers/test_model_wrapper.py

[Fix] Remove auto `find_ignored_modules`

---

.readthedocs.yml
docs/en/api/runner.rst
docs/zh_cn/api/runner.rst

[Fix] Fix docs

---

mmengine/model/wrappers/fully_sharded_distributed.py

[Fix] FSDP should call _get_ignored_modules

---

docs/en/notes/changelog.md
mmengine/version.py

bump version to v0.8.1

---

docs/en/notes/changelog.md
mmengine/version.py

Bump version to v0.8.2

---

docs/en/advanced_tutorials/registry.md

Try to clarify a bit more how registry works.
https://github.com/open-mmlab/mmengine/issues/1111
Added docs

Add short explanation about registry scope

---

mmengine/_strategy/fsdp.py

[Fix] Move data preprocessor to target device in FSDPStrategy

---

mmengine/model/base_module.py
tests/test_model/test_base_module.py

Support skipping initialization by setting `is_init=True`
See https://github.com/open-mmlab/mmpretrain/pull/1718 for more details.
If this PR introduces a new feature, it is better to list some use cases here, and update …

[Enhance] Support skipping initialization in `BaseModule`

---

mmengine/config/config.py

error message now:
```python
File :4
IndexError: list assignment index out of range
```
Enhanced:
```bash
File ~/codebase/mmengine/work_dirs/b.py:4
1 _base_ = []
3 a = []
----> 4 a[2] = 1
IndexError: list assignment index out of range
```
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep …

[Enhance] Ehance error message thrown by Config

---

README.md
README_zh-CN.md
docs/en/notes/changelog.md
mmengine/version.py

bump version to v0.8.3

---

mmengine/runner/_flexible_runner.py

Support callable collate_fn for FlexibleRunner
`mmengine/runner/_flexible_runner.py`
2. The …

[Enhance] Support callable collate_fn for FlexibleRunner

---

docs/en/common_usage/debug_tricks.md
docs/zh_cn/common_usage/debug_tricks.md

[Docs] Fix unused parameters

---

mmengine/config/utils.py

[Fix] fix config in colab

---

README.md
README_zh-CN.md
docs/en/notes/changelog.md
mmengine/version.py

bump version to v0.8.4

---

README.md
README_zh-CN.md

[Docs] Add a new ecosystem in README

---

.github/workflows/merge_stage_test.yml
.github/workflows/pr_stage_test.yml

Ignore examples in CI

---

docs/en/common_usage/visualize_training_log.md
docs/zh_cn/common_usage/visualize_training_log.md
mmengine/visualization/vis_backend.py

[Docs] Add a image for neptune

---

docs/en/api/strategy.rst
docs/en/common_usage/large_model_training.md
docs/zh_cn/api/strategy.rst
docs/zh_cn/common_usage/large_model_training.md
mmengine/_strategy/colossalai.py

[Docs] Fix docs of colossalai

---

mmengine/dist/dist.py

Fixed multi card issue in Pytorch version 2.1 on NPU.
Modify the dist.py file of the mmengine. …

[Fix] Fix multi card issue in PyTorch v2.1 on Ascend

---

mmengine/optim/optimizer/default_constructor.py
tests/test_optim/test_optimizer/test_optimizer.py

[Fix] Fix get optimizer_cls

---

mmengine/model/base_model/base_model.py

[Fix]Adapt to Pytorch version 2.1 on NPU.
Modify the mmengine/mmengine/model/base_model/base_model.py file. …

[Fix] Adapt to PyTorch v2.1 on Ascend

---

examples/distributed_training.py
mmengine/utils/progressbar.py

Refine error message

---

mmengine/utils/progressbar.py
tests/test_utils/test_progressbar.py

Fix the type check of tasks in progress bar

---

docs/en/common_usage/save_gpu_memory.md
docs/zh_cn/common_usage/save_gpu_memory.md

[Docs] Add activation checkpointing usage

---

docs/en/common_usage/better_optimizers.md
docs/zh_cn/common_usage/better_optimizers.md

Update the usage of bitsandbytes in Chinese document

---

tests/test_runner/test_amp.py

[Enhance] Add unit tests for autocast with Ascend device

---

mmengine/hooks/logger_hook.py

[Docs] Fix doc typo our_dir in LoggerHook

---

.github/CONTRIBUTING.md
.github/pull_request_template.md

[Docs] Add the contributing doc in pr template

---

docs/en/common_usage/better_optimizers.md
docs/en/common_usage/large_model_training.md
docs/en/common_usage/save_gpu_memory.md
docs/zh_cn/common_usage/better_optimizers.md
docs/zh_cn/common_usage/large_model_training.md
docs/zh_cn/common_usage/save_gpu_memory.md
mmengine/logging/logger.py
mmengine/visualization/vis_backend.py

v0.8.4 was released at 2023/08/03
1. Adafactor 2023/09/21 #1361
2. bitsandbytes 2023/09/15 #1357 
3. AimVisBackend 2023/09/09 #1347 
4. DVCLiveVisBackend 2023/09/08 #1336 
5. gradient checkpointing 2023/09/04 #1319 
6. MMLogger …

Update the version info

---

README.md
README_zh-CN.md
docs/en/notes/changelog.md
mmengine/version.py

bump version to v0.9.0

---

.circleci/test.yml
.github/workflows/merge_stage_test.yml
.github/workflows/pr_stage_test.yml

* Add torch 2.1.0 checking in CI
* Add "runs-on: macos-latest" in .github/workflows/pr_stage_text.yml
If so, please describe how it breaks the compatibility …

Add torch 2.1.0 checking in CI

---

docs/en/notes/contributing.md
docs/zh_cn/notes/contributing.md

[Docs] Rename master to main

---

mmengine/visualization/vis_backend.py

Resolve #1342
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this …

Fix new config in visualizer

---

mmengine/_strategy/deepspeed.py

Add `exclude_frozen_parameters` interface for `DeepSpeedStrategy.save_checkpoint`
`mmengine/_strategy/deepspeed.py`
If so, please describe how it breaks the compatibility and how the downstream projects should modify …

[Feature] Add `exclude_frozen_parameters` for `DeepSpeedStrategy`

---

examples/distributed_training_with_flexible_runner.py
mmengine/_strategy/deepspeed.py

[Enhancement] Enhance inputs_to_half in DeepSpeedStrategy

---

README.md
README_zh-CN.md
docs/en/notes/changelog.md
mmengine/version.py

bump version to v0.9.1

---

mmengine/_strategy/base.py
mmengine/_strategy/single_device.py
mmengine/runner/_flexible_runner.py

[Fix] Fix scale_lr in SingleDeviceStrategy

---

.github/workflows/merge_stage_test.yml
.github/workflows/pr_stage_test.yml
requirements/tests.txt
tests/test_visualizer/test_vis_backend.py

Fix CI for torch2.1.0.
The reason for removing **all** the tests on **macos** is that the tests would cause OOM on macos, causing the tests to fail, probably due to CI's device.
If so, please describe how it breaks the …

[Fix] Fix CI for torch2.1.0

---

README.md
README_zh-CN.md
docs/en/notes/changelog.md
mmengine/version.py

bump version to v0.10.0

---

.github/workflows/deploy.yml

[Fix] Fix deploy.yml

---

mmengine/utils/dl_utils/collect_env.py

[Fix] Fix collect_env without opencv

---

docs/en/get_started/installation.md
docs/zh_cn/get_started/installation.md

[Docs] Add build mmengine-lite from source

---

mmengine/utils/dl_utils/collect_env.py

Update collect_env.py: use ImportError to cover ModuleNotFoundError

---

docs/en/tutorials/hook.md
docs/zh_cn/tutorials/hook.md

[Docs] Add the usage of ProfilerHook

---

mmengine/config/config.py

Fix #1464 
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this …

[Fix] Fix `Config.to_dict`

---

mmengine/dist/dist.py

Before: `[[1, 2], [3, 4, 5, 6, 7], [8, 9, 10]] --> [1, 3, 8, 2, 4, 9]`
This PR: `[[1, 2], [3, 4, 5, 6, 7], [8, 9, 10]] --> [1, 3, 8, 2, 4, 9, 5, 10, 6, 7]` …

[Fix] Fix `dist.collect_results` to keep all ranks' elements

---

README.md
README_zh-CN.md
docs/en/notes/changelog.md
mmengine/version.py

Bump version to 0.10.3

---

README.md
README_zh-CN.md
docs/en/get_started/introduction.md
docs/zh_cn/get_started/introduction.md
requirements/docs.txt

Refine mmengine intro

---

mmengine/runner/loops.py

[Improve] Perform evaluation upon training completion

---

mmengine/_strategy/deepspeed.py

Enable `exclude_frozen_parameters` for `DeepSpeedEngine._zero3_consolidated_16bit_state_dict`
`mmengine/_strategy/deepspeed.py`
If so, please describe how it breaks the compatibility and how the downstream projects …

[Enhance] Enable `exclude_frozen_parameters` for `DeepSpeedEngine._zero3_consolidated_16bit_state_dict`

---

mmengine/config/utils.py

[Fix] Fix check builtin module

---

mmengine/logging/logger.py

Fix: return in finally

---

mmengine/optim/optimizer/builder.py
mmengine/registry/build_functions.py

ensure type in cfg
ensure type in cfg
If this PR introduces a new …

ensure type in cfg

---

.github/workflows/deploy.yml

[Enhance] Support trigger ci manually

---

.github/workflows/deploy.yml

[Enhance] Support trigger deploy CI manually

---

.github/workflows/deploy.yml

[Fix] Fix deploy ci

---

mmengine/registry/build_functions.py

[Fix] remove torch dependencies in `build_function.py`
