open-mmlab/mmengine

mmengine/visualization/vis_backend.py
'wandb add_image' does not upload images but array.
By using `wandb.Image`, it can upload images.
=> [BugFix] wandb image

mmengine/visualization/vis_backend.py
Related to https://github.com/open-mmlab/mmcv/pull/2237
```
vis_backends = [
dict(type='LocalVisBackend'),
dict(
type='WandbVisBackend',
init_kwargs=dict(
project='project', name='expname'),
define_metric_cfg={'coco/bbox_mAP': 'max'})
]
```
=> [Enhancement] wandb define_metric

mmengine/hooks/ema_hook.py, tests/test_hooks/test_ema_hook.py
When using yolox, it raised an error because of fixed num_classes in head.
```
File "/opt/site-packages/mmdet/.mim/tools/train.py", line 120, in <module>
main()
File "/opt/site-packages/mmdet/.mim/tools/train.py", line 116, in main
runner.train()
File "/opt/conda/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1623, in train
self.load_or_resume()
File "/opt/conda/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1585, in load_or_resume
self.load_checkpoint(self._load_from)
File "/opt/conda/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1977, in load_checkpoint
self.call_hook('after_load_checkpoint', checkpoint=checkpoint)
File "/opt/conda/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1693, in call_hook
getattr(hook, fn_name)(self, …
```
=> [bugfix] EMAHook load state dict

mmengine/hooks/checkpoint_hook.py, tests/test_hooks/test_checkpoint_hook.py
Fix `TypeError` when saving checkpoints if is `CheckpointHook` is constructed with argument `filename_tmpl`
- Add `filename_tmpl` to `CheckpointHook`'s keyword argument
- Add more unit tests
No
=> [Fix] CheckpointHook behavior incorrect if given `filename_tmpl` argument

mmengine/runner/checkpoint.py
In OpenMMLab 1.0, mmcv should be compatible with Pytorch1.5. Since `nn.Module` of Pytorch1.5  does not have `_non_persistent_buffers_set` attribute, therefore `_save_to_state_dict` will save registered buffer regardless of whether `persistent=True` or `persistent=False`.  
Pytorch 1.6:
```python
def _save_to_state_dict(self, destination, prefix, keep_vars):
for name, param in self._parameters.items():
if param is not None:
destination[prefix + name] = param if keep_vars else param.detach()
for name, buf in self._buffers.items(): …
```
=> [Fix] `_save_to_state_dict`

docs/zh_cn/tutorials/hook.md
=> fix a spell error in docs/zh_cn

mmengine/registry/build_functions.py
When using a custom runner, `runner_type` is not dumped appropriately, since `build_runner_from_cfg` function **pops** the `runner_type`.
To reproduce the experiment, it seems better to dump `runner_type` too.
https://github.com/open-mmlab/mmengine/blob/8d14eb65465785f8ec45bd8125a39c918f601b1f/mmengine/registry/build_functions.py#L179
=> [Fix] Use `get` instead of `pop` to dump `runner_type`

.pre-commit-config-zh-cn.yaml, .pre-commit-config.yaml, mmengine/config/config.py, mmengine/logging/logger.py, mmengine/optim/scheduler/param_scheduler.py, mmengine/runner/log_processor.py, setup.cfg
The motivation to upgrade some versions of pre-commit hooks to latest is that `importlib-metadata v5.0.0` which removed deprecated endpoint breaks the flake8. More details at https://stackoverflow.com/questions/73929564/entrypoints-object-has-no-attribute-get-digital-ocean/73932581#73932581.
Upgrade some versions of pre-commit hooks.
No
1. Pre-commit or other …
=> Upgrade pre commit hooks

docs/zh_cn/tutorials/hook.md, mmengine/model/averaged_model.py, mmengine/model/base_model/base_model.py, mmengine/model/wrappers/distributed.py, mmengine/model/wrappers/seperate_distributed.py
=> [Docs] Fix the docstring of model sub-package

docs/zh_cn/tutorials/registry.md
the input is randn, so we should delete the comment # tensor([-1.5774, -0.5850])
```shell
import torch
input = torch.randn(2)
output = model(input)
print(output)
```
delete the error comment
=> [Fix] delete the error comment

tests/data/config/py_config/test_get_external_cfg.py, tests/data/config/py_config/test_get_external_cfg2.py, tests/data/config/py_config/test_get_external_cfg3.py, tests/test_config/test_config.py, tests/test_dist/test_dist.py, tests/test_hub/test_hub.py
=> [Fix] some out-of-date unittests

mmengine/model/wrappers/fully_sharded_distributed.py
There is a typo in the FSDP wrapping policy.
=> [Fix] typo

mmengine/runner/log_processor.py
fix loss smooth when loss name doesn't start with `loss`, such as `Cascade RCNN` in mmdet and `RefineSingleStageDetector` in mmrotate. 
For example, loss may have prefix 's0.loss_xxx'.
cascade rcnn loss before:
```
09/19 11:31:38 - mmengine - INFO - Epoch(train) [1][500/6400]  lr: 2.5000e-03  eta: 6:32:10  time: 0.3258  data_time: 0.0035  memory: 4946  grad_norm: 6.8527  loss_rpn_cls: 0.1451  loss_rpn_bbox: 0.0861  s0.loss_cls: 0.2497  s0.acc: 94.9219  s0.loss_bbox: 0.0781  s1.loss_cls: 0.1206  s1.acc: 95.5078  s1.loss_bbox: …
```
=> [Fix] fix loss smooth when loss name doesn't start with `loss`

mmengine/model/base_model/base_model.py
Put the total loss in the log before all losses. total `loss` should be next to `grad_norm` 
Original log：
```bash
07/15 15:08:01 - mmengine - INFO - Epoch(train) [1][10/4]  lr: 1.0000e-02  eta: 0:00:00  time: 0.4341  data_time: 0.4319  memory: 0  grad_norm: 30.3858  loss_bbox: 9.6376  loss_cls: 9.6376  loss: 19.2753
```
Enhanced log：
```bash
07/15 15:06:04 - mmengine - INFO - Epoch(train) [1][10/4]  lr: 1.0000e-02  eta: 0:00:00  time: 0.0325  data_time: 0.0313  memory: 0  grad_norm: 23.0277  loss: 12.9813  loss_bbox: 6.4906 …
```
=> [Enhance] Put the total loss in the log before all losses

mmengine/hub/hub.py
In mmengine/hub/hub.py, the attribute `_is_init` of the model is set to True after loading checkpoint when `pretrained` is set to True so that the pretrained weights will not be overwritten.
=> [Fis] Set `_is_init` to True when `pretrained` is True

mmengine/model/base_model/data_preprocessor.py, tests/test_model/test_base_model/test_data_preprocessor.py
add non_blocking param to BaseDataPreprocessor, which transfer tensor to device asynchronously. See https://pytorch.org/docs/stable/generated/torch.Tensor.to.html#torch.Tensor.to for detail.
add non_blocking param to BaseDataPreprocessor.
Every DataPreprocessor should add non_blocking param.
User can set pin_memory and non_blocking to True to transfer tensor from cpu to gpu asynchronously, instead of blocking the process when transfer data.
=> add non_blocking feature to BaseDataPreprocessor

mmengine/runner/log_processor.py, mmengine/runner/loops.py
The log information of total iterations is float type when using `IterBasedTrainLoop`.
Related issue: #603 
1. …
=> [FIx] Fix the total number of iterations in log is a float number.

mmengine/dataset/utils.py, mmengine/runner/amp.py, tests/test_runner/test_amp.py
Make autocast compatible with MPS #566
1. Pre-commit or other linting tools are used to fix the potential lint …
=> [Fix] Make autocast compatible with mps

docs/en/get_started/15_minutes.md, docs/en/get_started/installation.md
Translate documents
docs/en/get_started/15_minutes.md
docs/en/get_started/installation.md
4. The …
=> [Docs] Translate installation and 15_min

mmengine/utils/dl_utils/collect_env.py
Refer to https://github.com/open-mmlab/mmcv/pull/1918. …
=> Add ROCm info when collecting env

mmengine/evaluator/evaluator.py, tests/test_evaluator/test_evaluator.py
BaseDataset does not support slice index which is used in `offline_evaluate`.
Replace slice index with `get_chunks` to get a batch of data.
None.
=> [Fix] Fix offline eval dataset index error.

docs/en/api/optim.rst, docs/zh_cn/api/optim.rst, mmengine/hooks/checkpoint_hook.py, mmengine/optim/optimizer/__init__.py, mmengine/optim/optimizer/zero_optimizer.py, tests/test_optim/test_optimizer/test_optimizer.py
- Device: V100 32GB (32510MiB) x4
- Input Size: 512
- Total Batch Size: 16
|  Method  |      Time       |  Memory  |
| :------: | :-------------: | :------: |
| w/o zero | 0.611 | 7053|
| w/  zero | 0.552 | 6868 |
Time may be dependent to the environment.
Co-authored-by: Junhwa Song <ethan9867@gmail.com> @KKIEEK
Signed-off-by: Junhwa Song <ethan9867@gmail.com>
Signed-off-by: Hakjin Lee <nijkah@gmail.com>
=> [Feature] Support torch ZeroRedundancyOptimizer

mmengine/hooks/ema_hook.py
Resolve #607.
Since #542 makes `load_state_dict` not save or load non-persistent buffer anymore, resuming the old checkpoint with `std` and `mean` will cause the error described in #607. 
The default resume strategy of `EMAHook` should be consistent with `Runner`. Since `Runner` does not load checkpoint strictly, the default value of `load_strict` in `EMAHook` should be False.
Does the modification introduce changes that break the backward-compatibility of the …
=> Change strict_load of EMAHook to False by default

mmengine/optim/scheduler/param_scheduler.py, tests/test_optim/test_scheduler/test_param_scheduler.py
=> [Fix] fix CosineRestart eta_min

mmengine/config/config.py
Fix open() encoding problem of Config in Windows …
=> fix config encoding

docs/zh_cn/tutorials/config.md, mmengine/config/utils.py, mmengine/hub/hub.py, tests/test_hub/test_hub.py
MMdetection has renamed some configs https://github.com/open-mmlab/mmdetection/tree/3.x/configs
The docstring and documentation used in mmengine.hub.get_model should be updated. 
'faster_rcnn' -> 'faster-rcnn'
If this PR introduces a new feature, it is better to list some use cases …
=> [Docs] fix docstring and documentation used for hub.get_model

mmengine/model/weight_init.py
If a checkpoint is saved with `map_location='cuda:0'`, `PretrainedInit` will first load the checkpoint to "cuda:0", and then copy the parameters to the model. During ddp-training, all ranks will first load the checkpoint to "cuda:0", which could cause an OOM error.
A workaround could be that let `PretrainedInit` load the checkpoint to "cpu" by default.
If so, please …
=> [Fix] Fix potential OOM error when loading checkpoint with `map_location="cuda:0"`

docs/zh_cn/tutorials/evaluation.md
=> [Docs] Fix evaluator type name

mmengine/hooks/checkpoint_hook.py
Resolve https://github.com/open-mmlab/mmyolo/issues/244.
1. Pre-commit or other linting tools are used to fix …
=> [Fix] Fix error when saving best checkpoint in ddp-training.

mmengine/dataset/base_dataset.py
=> [Fix] Fix basedataset typo about lazy initialization

.gitignore, mmengine/hooks/hook.py, mmengine/runner/runner.py, tests/test_runner/test_runner.py
This PR is linked to https://github.com/open-mmlab/mmengine/issues/599
I added the test of `runner.get_hook_info()` in `tests/test_runner/test_runner.py`
=> [Feature] Add test of get_hooks_info()

mmengine/optim/scheduler/lr_scheduler.py, mmengine/optim/scheduler/momentum_scheduler.py, mmengine/optim/scheduler/param_scheduler.py, tests/test_optim/test_scheduler/test_param_scheduler.py
[Enhance] support eta_min_ratio in CosineAnnealingParamScheduler
[doc] fix a typo in CosineRestartParamScheduler's docstring
=> [Enhance] support eta_min_ratio in CosineAnnealingParamScheduler

mmengine/model/utils.py, tests/test_model/test_model_utils.py
Resolve #638
2. The modification …
=> [Enhance] Enhance compatibility of `revert_sync_batchnorm`

mmengine/structures/base_data_element.py, tests/test_structures/test_data_element.py
Remove the redundant inner attribute created by the property function
Before:
```python
class DetDataSample(BaseDataElement):
@property
def proposals(self):
return self._proposals
@proposals.setter
def proposals(self, value):
self.set_field(value=value, name='_proposals', dtype=BaseDataElement)
@proposals.deleter
def proposals(self):
del self._proposals
data_sample = DetDataSample(proposals=InstanceData())
print(data_sample.keys())
```
```
['proposals', '_proposals']
```
```python
print(data_sample)
```
```
<DetDataSample(
META INFORMATION
DATA FIELDS
proposals: <InstanceData(
META INFORMATION
DATA FIELDS
) at 0x7fa086437820>
_proposals: <InstanceData(
META INFORMATION
DATA FIELDS
) at 0x7fa086437820>
) at 0x7fa086437910>
```
After:
```python
print(data_sample.keys())
```
``` …
```
=> [Enchance] remove redundant attribute in dump or print

mmengine/hub/hub.py
mmcls moved some `data_preprocessor` field to config file's root field, instead of model's field. Runner changed logic to adapt to this change, but hub didn't.
Before this PR:
```python
model = mmengine.hub.get_model('mmcls::deit/deit-small_pt-4xb256_in1k.py')
model.data_preprocessor.num_classes
```
After this PR:
```python
model = mmengine.hub.get_model('mmcls::deit/deit-small_pt-4xb256_in1k.py')
model.data_preprocessor.num_classes
```
Does the modification introduce …
=> [Fix] hub.get_model fails on some mmcls models

docs/en/api/infer.rst, docs/zh_cn/api/infer.rst, mmengine/infer/infer.py
=> [Fix] Minor refine to inference

mmengine/model/base_model/base_model.py, mmengine/model/base_model/data_preprocessor.py, tests/test_model/test_base_model/test_base_model.py
Make `BaseModel.to` and `BaseDataPreprocessor.to` methods to be consistent with `torch.nn.Module.to`, i.e. it can accept devices and dtypes as arguments and handle these cases properly.
Before this PR:
```python
class Model(BaseModel):
def __init__(self):
super().__init__()
self.linear = nn.Linear(4, 4)
def forward(self):
pass
model = Model()
model.to('cuda')  # correct
model.to(torch.half)  # raise TypeError
model.to(device='cuda', dtype=torch.half)  # no exception, but dtype ignored
```
After this PR:
```python …
```
=> [Fix] BaseModel & BaseDataPreprocessor `to` method to be consistent with torch.nn.Module

docs/en/advanced_tutorials/config.md, docs/zh_cn/advanced_tutorials/config.md, mmengine/config/config.py, tests/test_config/test_config.py
Sometimes, we want to create a bash script with some default `--cfg-options`, like
```bash
python tools/train.py $1 --cfg-options default_hooks.checkpoint.save_best=True ${@:2}
```
but when we use the script, and pass another `--cfg-options` to it, the last one will overwrite the previous completely.
According to the [`extend` action](https://docs.python.org/3/library/argparse.html#action) of Python, I modified the `DictAction` in MMEngine, and now it supports multiple `--cfg-options` and will concat these options.
Almost not, unless users exactly use multiple options and want the last one to overwrite the previous one.
```bash
python tools/train.py $1 --cfg-options default_hooks.checkpoint.save_best=True --cfg-options train_cfg.max_epochs=300
```
And we will get both options.
1. …
=> [Enhance] Support multiple `--cfg-options`.

docs/en/advanced_tutorials/data_transform.md, docs/en/conf.py, docs/en/migration/transform.md, docs/zh_cn/advanced_tutorials/data_transform.md, docs/zh_cn/conf.py, docs/zh_cn/migration/transform.md
Add data transform doc translation.
Add data transform doc translation. And modify the intersphinx link to mmcv.
=> [Docs] Translate data transform docs.

docs/en/api/infer.rst, docs/en/index.rst, docs/zh_cn/api/infer.rst, docs/zh_cn/index.rst, mmengine/infer/infer.py, tests/test_infer/test_infer.py
`inferencer.visualize` needs the original inputs rather than the preprocessed inputs to show the visualization result, therefore we need to pass the original inputs to `visualize`. 
This PR extract some logics from `preprocess` to `preprocess_data`, which is responsible for listing the files from a directory and converting the inputs to a list. `__call__` will call preprocess_data and pass the returned value to `visualize`
Does the modification introduce changes that …
=> [Fix] Add preprocess inputs to inference

mmengine/optim/optimizer/optimizer_wrapper.py, mmengine/optim/optimizer/optimizer_wrapper_dict.py
`optimizer.step()` supports kwargs (https://github.com/open-mmlab/mmengine/blob/main/mmengine/optim/optimizer/optimizer_wrapper.py#L211), but` update_params` not (https://github.com/open-mmlab/mmengine/blob/main/mmengine/optim/optimizer/optimizer_wrapper.py#L176).
this would be a problem if I want to write my own model wrapper. 
Add kwargs to update_params …
=> [Enhance] Support pass arugments with update_params

docs/en/advanced_tutorials/basedataset.md, docs/zh_cn/advanced_tutorials/basedataset.md, mmengine/visualization/visualizer.py
=> [Docs] Fix docstring format and rescale the images

docs/en/conf.py, docs/zh_cn/conf.py, mmengine/registry/build_functions.py, mmengine/registry/default_scope.py
=> [Docs] Fix failed link in registry

mmengine/runner/checkpoint.py, tests/test_runner/test_checkpoint.py
Pick commit from https://github.com/open-mmlab/mmcv/pull/2246.
1. Pre-commit or other linting tools are used to …
=> [Enhance] Enhance get_torchvision_model

mmengine/optim/optimizer/zero_optimizer.py, tests/test_optim/test_optimizer/test_optimizer.py
See issue #778 
Add check for param groups and torch version, and give a better instruction to users.
No
Same as before
4. The documentation has been modified accordingly, like docstring or …
=> [Fix] ZeroRedundancyOptimizer ambiguous error with param groups when pytorch < 1.12.0

examples/distributed_training.py, mmengine/logging/message_hub.py
Fix `MessageHub.update_info` set resumed key twice. …
=> [Fix] Fix MessageHub set resumed key repeatedly

docs/en/advanced_tutorials/registry.md, docs/en/api/registry.rst, docs/zh_cn/advanced_tutorials/registry.md, docs/zh_cn/api/registry.rst, mmengine/registry/__init__.py, mmengine/registry/registry.py, mmengine/registry/utils.py, mmengine/runner/runner.py, tests/test_registry/test_registry_utils.py
Support auto-import modules from pre-defined locations.
Use lazy import during building to avoid registering useless modules at the beginning.
Modify the `get` method.
in mmdet/registry.py
```python
DATASETS = Registry('dataset', parent=MMENGINE_DATASETS, locations=['mmdet.datasets'])
DATA_SAMPLERS = Registry('data sampler', parent=MMENGINE_DATA_SAMPLERS, locations=['mmdet.datasets.samplers'])
TRANSFORMS = Registry('transform', parent=MMENGINE_TRANSFORMS, locations=['mmdet.datasets.transforms'])
```
and then the …
=> [Feature] Support registry auto import modules.

mmengine/runner/checkpoint.py
Fixes https://github.com/open-mmlab/mmengine/issues/755
Checks if tty-like environment when using torch progress bars
No 
3. If the modification has potential influence on downstream projects, this PR should be tested with downstream …
=> add progress arg

mmengine/hooks/checkpoint_hook.py, tests/test_hooks/test_checkpoint_hook.py
Resolve #845
During initial training, metrics produced by the poor model may be an empty dict and it will cause errors when saving the best checkpoints by CheckpointHook. Therefore, this PR ensures metrics are not empty before saving the best checkpoints.
Add checking for metrics in CheckpointHook.after_val_epoch method.
No
2. The modification …
=> [Enhance] Ensure metrics is not empty when saving best ckpts

mmengine/config/config.py, tests/test_config/test_config.py
=> [Fix] Fix `Config` cannot parse base config when there is `.` in tmp path, etc. `tmp/a.b/c`

mmengine/device/utils.py, mmengine/model/base_model/base_model.py, mmengine/model/base_model/data_preprocessor.py, mmengine/structures/base_data_element.py
Supplement the support of some functions on the NPU
1. mmengine/model/base_model/base_model.py Added the to function that adapts to NPU and npu function.
2. mmengine/model/base_model/data_preprocessor.py Added the to function that adapts to NPU and npu function.
3. mmengine/structures/base_data_element.py Added npu function.
=> [Fix] Add support for Ascend device

mmengine/hooks/logger_hook.py, mmengine/hooks/runtime_info_hook.py, mmengine/runner/log_processor.py, tests/test_hooks/test_logger_hook.py, tests/test_runner/test_log_processor.py
In the original implementation, the `RuntimeInfoHook` will raise an error if the metric value is not a scalar. But some metric result is non-scalar type, like confusion-matrix.
If the metric value is not scalar, the value will be saved into the `runtime_info`. And in the `LogProcessor`, it will extract runtime info according to the mode.
No
```
01/10 10:59:49 - mmengine - INFO - Load checkpoint from /home/PJLAB/mazerun/ckpt/v0/resnet/resnet18_b16x8_cifar10_20210528-bd6371c8.pth
01/10 10:59:51 - mmengine - INFO - Epoch(test) [100/625]    eta: 0:00:08  time: 0.0068  data_time: 0.0001  memory: 84  
01/10 10:59:51 - mmengine - INFO - Epoch(test) [200/625]    eta: 0:00:04  time: 0.0068  data_time: 0.0001  memory: 85  
01/10 10:59:52 - mmengine - INFO - Epoch(test) [300/625]    eta: 0:00:03 …
```
=> [Enhance] Support non-scalar type metric value.

mmengine/dataset/utils.py, mmengine/runner/runner.py
Disable warning of subprocess launched by dataloader. Since [this PR in MMCV](https://github.com/open-mmlab/mmcv/pull/2539) will raise a warning in transform, duplicated warnings raised by subprocesses will be shown in the terminal if `num_workers > 1` is set for the `Dataloader`.
This PR provides an option to disable all warnings of subprocesses, such as:
```python
train_dataloader = dict(
...
disable_subprocess_warning=True
)
```
Does the modification introduce …
=> [Enhance] Disable warning of subprocess launched by dataloader

docs/en/api/infer.rst, docs/en/index.rst, docs/zh_cn/api/infer.rst, docs/zh_cn/index.rst, mmengine/infer/__init__.py, mmengine/infer/infer.py, mmengine/registry/registry.py, mmengine/testing/runner_test_case.py, requirements/runtime.txt, tests/test_infer/test_infer.py
Add `BaseInferencer` for providing an easy and clean interface for single or multiple images inferencing.
```python
class XXXInferencer(BaseInferencer):
...
inferencer = XXXInferencer(model='path-to-config', weights='path-to-checkpoint', device='cuda')
results = inferencer('img or filename or directory')
predictions = results['predictions']
visualization = results['visualization']
```
Based on `BaseInferencer`, the `__init__` of subclasses should at least accept 3 arguments: 
- model: model could be many types:
- model name …
=> [Feature] Add `BaseInferencer` to MMEngine

docs/en/advanced_tutorials/config.md, docs/resources/config/replace_data_root.py, docs/resources/config/replace_num_classes.py, docs/zh_cn/advanced_tutorials/config.md, mmengine/config/config.py, tests/data/config/py_config/test_environment_var.py, tests/data/config/py_config/test_predefined_var.py, tests/test_config/test_config.py
Enable using environment variables in config files. Can make config more flexible.
demo_config.py
```
dataset_type = 'CocoDataset'
data_root = '{{$MMDET_DATASET:/data/coco/}}'
file_client_args = dict(backend='disk')
```
test.py
```
from mmengine.config import Config
cfg = Config.fromfile('demo_config.py')
print(cfg)
```
The results of this pr are as below:
```
>> python test.py
Config (path: demo_config.py): {'dataset_type': 'CocoDataset', 'data_root': '/data/coco/', 'file_client_args': {'backend': 'disk'}}
>> …
```
=> [Enhance] Substitute the environment variable in config file.

mmengine/fileio/io.py, tests/test_fileio/test_io.py
```python
>>> import mmengine.fileio as fileio
>>> backend_args = {'backend': 'local'}
>>> res = fileio.get(filepath, backend_args=backend_args)
>>> backend_args
{}
```
`backend` key in `backend_args` will be popped and it will cause the program to fail when users use it again.
copy `backend_args` before popping it.
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code …
=> [Fix] backend_args should not be modified by get_file_backend

docs/en/advanced_tutorials/distributed.md, mmengine/dist/utils.py, mmengine/runner/runner.py, requirements/tests.txt
This PR fixes https://github.com/open-mmlab/mmengine/issues/873:
* Adds option to specify a runtime timeout for distributed training
* Safe conversion of the specified timeout in seconds to `timedelta` with type-check
* Adding documentation on how to use it
=> [Enhancement] Enable timeout in dist training

docs/en/api/optim.rst, docs/zh_cn/api/optim.rst, mmengine/optim/__init__.py, mmengine/optim/optimizer/__init__.py, mmengine/optim/optimizer/apex_optimizer_wrapper.py, tests/test_optim/test_optimizer/test_optimizer_wrapper.py
Add ApexOptimWrapper for mmengine.
1. Pre-commit or other linting tools are used …
=> [Feature] Add ApexOptimWrapper

mmengine/registry/registry.py, requirements/runtime.txt, tests/test_registry/test_registry.py
For better debug usages
- requirements/runtime.txt
- add tabulate requirement
- mmengine\registry\registry.py
- use tabulate to format the repr str
- tests\test_registry\test_registry.py
- modify the repr test
3. If the modification has potential influence on downstream projects, this PR should be tested with downstream projects, like …
=> [Enhance] beautify the print result of the registry

.readthedocs.yml, docs/en/advanced_tutorials/test_time_augmentation.md, docs/en/notes/contributing.md, docs/zh_cn/advanced_tutorials/test_time_augmentation.md, docs/zh_cn/notes/contributing.md
PR #915 spoiled docs building process in readthedocs. Reasons under investigation. This PR temporarily disabled building pdf docs to skip this error.
4. The documentation has been modified …
=> [Docs] Temporarily skip errors in building pdf docs at readthedocs

mmengine/optim/optimizer/default_constructor.py, tests/test_optim/test_optimizer/test_optimizer.py
```
import torch.nn as nn
from mmcv.cnn import ConvModule
from mmengine.optim import (OptimWrapper, OptimWrapperDict, build_optim_wrapper)
from mmengine import Config, ConfigDict
from torch.optim import Optimizer
from collections import OrderedDict
class Net(nn.Module):
def __init__(self):
super().__init__()
toy_modules = nn.ModuleList()
toy_modules.append(ConvModule(1, 1, 1))
toy_modules.append(ConvModule(1, 1, 1))
toy_modules[-1].conv = toy_modules[0].conv
self.toy_modules = toy_modules
def forward(self, x):
for module in self.toy_modules:
x = module(x)
return x
def my_build_optim_wrapper(optim_wrapper, model):
if isinstance(optim_wrapper, OptimWrapper):
return optim_wrapper
if isinstance(optim_wrapper, (dict, ConfigDict, Config)):
optimizer = optim_wrapper.get('optimizer', None)
if …
```
=> [Bug] Fix the bug when the params in shared modules do not require grad

mmengine/registry/registry.py, tests/test_registry/test_registry.py
When calling `a = repr(OPTIMIZERS)`, nothing should be printed.
- Before this PR
```python
import mmengine.optim
from mmengine.registry import OPTIMIZERS
a = repr(OPTIMIZERS)  # print a table. It should not print anything.
```
- After this PR
```python
import mmengine.optim
from mmengine.registry import OPTIMIZERS
a = repr(OPTIMIZERS)  # do not print a table
```
```python
print(a)
```
```python
>>> OPTIMIZERS
```
No
If this PR introduces a new feature, it is better to …
=> Refine the repr of Registry

docs/en/api/hooks.rst, docs/zh_cn/api/hooks.rst, mmengine/hooks/__init__.py, mmengine/hooks/profiler_hook.py, tests/test_hooks/test_profiler_hook.py
Added NPUProfilerHook class.
No.
```python
cfg = Config.fromfile(args.config) 
profiler_config = [dict(type='NPUProfilerHook', result_path='./cann_profiling')]
cfg.merge_from_dict({'custom_hooks': profiler_config })
runner = Runner.from_cfg(cfg)
```
Export timeline data
python /usr/local/Ascend/ascend-toolkit/latest/toolkit/tools/profiler/profiler_tool/analysis/msprof …
=> [Feature] Feature NPUProfilerHook

mmengine/hooks/ema_hook.py, tests/test_hooks/test_ema_hook.py
=> [Refactor] Refactor ema hook

docs/en/common_usage/epoch_to_iter.md, docs/en/get_started/15_minutes.md, docs/en/index.rst, docs/zh_cn/common_usage/epoch_to_iter.md, docs/zh_cn/index.rst, mmengine/runner/runner.py
=> [Docs] Add the document for the transition between IterBasedTraining and EpochBasedTraining

mmengine/hooks/ema_hook.py, mmengine/hooks/hook.py, tests/test_hooks/test_ema_hook.py, tests/test_hooks/test_empty_cache_hook.py, tests/test_hooks/test_hook.py, tests/test_hooks/test_iter_timer_hook.py, tests/test_hooks/test_param_scheduler_hook.py, tests/test_hooks/test_runtime_info_hook.py, tests/test_hooks/test_sampler_seed_hook.py
- Refactor unit test of Base hook #806
- Refactor unit test of EmptyCacheHook #805
- Refactor unit test of IterTimerHook #807 
- Refactor unit test of DistSamplerHook #812
- Refactor unit test of RuntimeInfoHook #810 
- Refactor unit test of ParamSchedulerHook #809
- Refactor unit test of EMAHook #804
If so, please describe how it breaks the compatibility and how the …
=> Refactor hooks unittest

mmengine/utils/dl_utils/collect_env.py
See issue #931 
There might also be some corner cases that raises error during collecting compiler information. We should not stop the user's program from running due to these exceptions.
Captures all exceptions and records the reason instead of raises exceptions.
No
3. If the modification has potential influence on downstream projects, …
=> [Fix] Temporarily fix `collect_env` raise errors and stops programs

mmengine/infer/infer.py
Sometimes, downstream developers would like to set `PYTHONPATH=xxx` rather than install the package by `pip install -e .`. , then and `BaseInferencer` will raise an error in this case.
This PR will get the module path from `module.__path__` and do not check the installation of the downstream repos anymore. It will try to get the directory of `Config` from `${module._path}/.mim` (package is installed) or ``../${module._path}`` (package is not installed, but PYTHONPATH is set).
Please briefly describe what modification is made in …
=> [Enhance] Get model configs from model-index without installation

docs/en/common_usage/speed_up_training.md, docs/zh_cn/common_usage/speed_up_training.md, mmengine/optim/optimizer/amp_optimizer_wrapper.py, tests/test_optim/test_optimizer/test_optimizer_wrapper.py
Enable `torch.bfloat16` in `AmpOptimWrapper` and config file
New optional argument `dtype` in `AmpOptimWrapper`, can be `str` or `torch.dtype`
No
```python
optim_wrapper = dict(
type='AmpOptimWrapper',
dtype='bfloat16',  # (None, float32, float16, bfloat16, ...)
....
)
```
| setting | iter_time | memory | acc_top1 | acc_top5 |
|  :---      |    :---:      |  :---: | :---: | :---: |
| no amp                          | 0.4230 | 21665 | 78.30 | 93.80 |
| amp float16                   | 0.4239 | 11481 | -- | -- |
| amp bfloat16 …
=> [Feature] enable bf16 in AmpOptimWrapper

mmengine/dataset/base_dataset.py, mmengine/dataset/dataset_wrapper.py, mmengine/evaluator/metric.py, mmengine/fileio/backends/base.py, mmengine/fileio/file_client.py, mmengine/hooks/checkpoint_hook.py, mmengine/hooks/logger_hook.py, mmengine/hooks/profiler_hook.py, mmengine/model/averaged_model.py, mmengine/model/base_module.py, mmengine/optim/optimizer/default_constructor.py, mmengine/registry/utils.py, mmengine/runner/checkpoint.py, mmengine/runner/loops.py, mmengine/runner/runner.py, mmengine/visualization/visualizer.py, tests/test_evaluator/test_evaluator.py, tests/test_hooks/test_checkpoint_hook.py, tests/test_hooks/test_logger_hook.py, tests/test_hub/test_hub.py, tests/test_model/test_averaged_model.py, tests/test_optim/test_optimizer/test_optimizer.py, tests/test_registry/test_registry_utils.py, tests/test_runner/test_runner.py, tests/test_visualizer/test_visualizer.py
Replace `warnings.warn` with `print_log` in some modules to avoid throwing duplicated warnings during DDP training. The basic rules are:
1. Those warnings could be raised in DDP training.
2. Functions that throw these warnings will not be called repeatedly during training.
The original warning caused by dataset:
```shell
/home/yehaochen/codebase/mmengine/mmengine/runner/loops.py:56: UserWarning: Dataset CIFAR10 has no metainfo. ``dataset_meta`` in visualizer will be None.
warnings.warn( …
```
=> [Enhancement] Replace `warnings.warn` with `print_log`

mmengine/runner/log_processor.py
add memory in other log
add memory in other log
2. The modification is covered by complete …
=> [Enhancement] Save the memory to visualization backends

mmengine/analysis/jit_handles.py, tests/test_analysis/test_flop_count.py
If user write the code like:
```python
import torch
import torch.nn as nn
from mmengine.analysis import flop_count
class MatmulNet(nn.Module):
"""A network with a single torch.matmul operation.
This is used for testing flop count for torch.matmul.
"""
def __init__(self) -> None:
super().__init__()
def forward(self, x: torch.Tensor, y: torch.Tensor) -> torch.Tensor:
x = torch.matmul(x, y)
return x
m = 20
n = 10
p = 1
m_net = MatmulNet()
x = torch.randn(m, n)
y = torch.randn(n)
flop_dict, _ = flop_count(m_net, (x, y))
``` …
=> [Fix] Support calculate the flops of `matmul` with single dimension matrix

docs/en/common_usage/speed_up_training.md, docs/zh_cn/common_usage/speed_up_training.md, mmengine/runner/runner.py, tests/test_runner/test_runner.py
Support `torch.compile` introduced in PyTorch 2.0
Check for `compile` keyword in config dict. If not None, will call `torch.compile` according to its options.
No
Add a single line (or a few lines) in your config file.
```python
compile = True
```
You can pass arguments to `torch.compile`, as described in [PyTorch Documentation](https://pytorch.org/docs/master/generated/torch.compile.html#torch.compile)
```python
compile = dict(
backend='inductor',
mode='reduce-overhead'
)
```
Due to a [PyTorch mkldnn …
=> [Feature] Add configurations to support torch.compile in Runner

examples/distributed_training.py, mmengine/hooks/logger_hook.py, mmengine/runner/log_processor.py, tests/test_hooks/test_logger_hook.py, tests/test_runner/test_log_processor.py
1. Support log information to various backends(Tensorboard, WandB) with **hierarchy**
2. Count averaged `time` and `data_time` **by epoch during validation**
Enable `log_with_hierarchy` in `LogProcessor`
```python
log_processor = dict(
log_with_hierarchy=False
)
```
**original layout**:
**hierarchy layout**
As you can see, logs are divided into `train` and `val`, and the averaged `time`, `data_time` during validation is counted.
Does the modification introduce changes …
=> [Enhance] Support writing data to `vis_backend` with prefix

mmengine/device/utils.py, mmengine/runner/amp.py
1. Support automatic mixed-precision training with pytorch version 1.10 or above.
2. Support manually set up the use of dynamic shapes and static shapes.
1. mmengine/runner/amp.py. complements to NPU autocast.
2. mmengine/device/utils.py. supplemented with a switch to turn on static shape，dynamic shapes are used by default.
None.
Open the static shape：export  NPUJITCompile=True
1. Pre-commit or other linting tools are used to …
=> [Fix] Fix AMP in Ascend and support using NPUJITCompile environment

.circleci/test.yml, mmengine/infer/infer.py, tests/test_infer/test_infer.py
Fix inferencer get wrong configs path.
1. Pre-commit or other linting tools are used to fix the potential lint …
=> [Fix] Fix inferencer gets wrong configs path

mmengine/structures/base_data_element.py
Same for #690 
PyTorch2.0 does not support sys._getframe, so we remove the redundant inner attribute created by the property function by removing the `_` + property_name at the `keys()` function.
=> [Fix] fix pytorch2.0 not support sys._getframe to remove private key

mmengine/model/base_module.py, mmengine/model/utils.py, mmengine/runner/runner.py, mmengine/visualization/vis_backend.py
There are 2 cases:
1. Use print_log, when there is no logger/self.logger.
2. Use logger/self.logger, when print_log and logger/self.logger are present at the same time.
If this PR introduces …
=> [Enhancement] Unify the use of print_log and logger

mmengine/device/utils.py
Determine devices on initialization instead of whenever `get_device` is called.
Determine the availability of NPU devices on initialization instead of whenever `is_npu_available` is called.
Add new variables `IS_NPU_AVAILABLE` and `DEVICE`
No
Not changed
3. If the modification has potential influence on downstream projects, this PR …
=> [Refactor] `get_device` and `is_npu_available`

docs/en/advanced_tutorials/basedataset.md, docs/en/advanced_tutorials/config.md, docs/en/advanced_tutorials/initialize.md, docs/en/advanced_tutorials/test_time_augmentation.md, docs/en/migration/runner.md, docs/en/tutorials/model.md, docs/en/tutorials/optim_wrapper.md, docs/en/tutorials/param_scheduler.md
While attempting to `sphinx-build` a `latexpdf` of the EN docs on latest master, I encountered several build failures due to the usage of various non-ascii chars.
For example:
- 'Full-width' punctuation chars instead of normal ascii: 
- `：` vs `:`
- `（）` vs `()`
- `，` vs `,`
- etc..
- Various `zh_cn` comments in documented code-blocks
The use of "full-width" chars (also referred to as 'double-byte' in JIS encoding) can cause issues with certain Sphinx build target formats (such as `latexpdf`).
They can also cause various other issues for users, especially users who can only reference EN documentation, who may not have a device with Asian language support.
As such, to allow for smoother docs builds and for usability/readability for EN-based users, our EN docs should be constrained to the …
=> [Docs] Minor fixes in EN docs to remove or replace unicode chars with ascii

mmengine/runner/log_processor.py, tests/test_runner/test_log_processor.py
Resolve #1016 .
before:
```bash
03/28 18:54:17 - mmengine - INFO - Epoch(val) [1][157/157]  accuracy: 28.8200data_time: 0.0049  time: 0.0101
```
after:
```bash
03/28 18:53:03 - mmengine - INFO - Epoch(val) [1][157/157]  accuracy: 29.1400  data_time: 0.0050  time: 0.0101
```
If so, please describe how it breaks the compatibility and how the downstream projects should …
=> [Fix] Fix there is no space between data_time metric

docs/en/tutorials/hook.md, docs/zh_cn/tutorials/hook.md, mmengine/hooks/checkpoint_hook.py, tests/test_hooks/test_checkpoint_hook.py
As https://github.com/open-mmlab/mmengine/issues/905 described.
[Enhancement] add automatically Publish in checkpointhook.py and corresponding update document in hook.md
3. If the modification has potential influence on downstream projects, this PR should be tested with downstream projects, like MMCls.
For example：
I am training cifar10 using the resnet50 model from the code in the mmengine example …
=> [Feature] Publish models after training if  published_keys is set in CheckpointHook

.github/workflows/merge_stage_test.yml, .github/workflows/pr_stage_test.yml
Github Action CI could throw errors randomly when testing `test_dist` due to machine's capability. This PR skip testing `test_dist` in all Github Action CI, and only test `test_dist` in circle CI.
If this PR introduces a …
=> [Fix] Skip testing `test_dist` in Github Action CI

mmengine/runner/log_processor.py, tests/test_runner/test_log_processor.py
The aligned log  is shown in the following figure
1. Pre-commit or other linting …
=> [Enhancement] Align the evaluation result in log

mmengine/dataset/dataset_wrapper.py
Related PR: https://github.com/open-mmlab/mmdetection/pull/10038
Right now, if the `cat_ids` is empty, the operation will be skipped. And the length of the repeat_factors will not equal to len(self.dataset). 
https://github.com/open-mmlab/mmengine/blob/093068e4ffdb0bb6ab0b95c45d9616835e930ce0/mmengine/dataset/dataset_wrapper.py#L430-L437
The index of the image without any label will be replaced by the next image, and this will cause error.
https://github.com/open-mmlab/mmengine/blob/093068e4ffdb0bb6ab0b95c45d9616835e930ce0/mmengine/dataset/dataset_wrapper.py#L383-L391
Hence, if the image label is empty, it should add`1.0` in `repeat_factors` to keep the length same.
```
Epoch(val) [12][2477/2477]  
lvis/bbox_AP: 0.2160  lvis/bbox_AP50: 0.3520  lvis/bbox_AP75: 0.2290  lvis/bbox_APs: 0.1660 …
```
=> [Fix] Update the ClassBalancedDataset logic

mmengine/structures/instance_data.py
When we test the ssd model on the NPU, an assert error occurs during the eval phase, because npu.BoolTensor and npu.LongTensor are not supported in instane_data.py.
Modify the instane_data.py file to support NPU BoolTensor and LongTensor.
Not affected.
Not affected.
=> [Enhancement] Support BoolTensor and LongTensor on Ascend NPU

mmengine/analysis/print_helper.py
Optimize the flexibility of function `get_model_complexity_info()`. #1055
1. Set default value of `input_shape` to `None`.
2. `assert` does not allow both `input_shape` and `inputs` are `None`.
3. If both `input_shape` and `inputs` are provided, print a warning.
It the downstream repo calls the function `get_model_complexity_info()` like [this line](https://github.com/open-mmlab/mmdetection/blob/ecac3a77becc63f23d9f6980b2a36f86acd00a8a/tools/analysis_tools/get_flops.py#L99) (It seems that the downstream repos have to call this function like the linked line.), not change has to be performed on the existing repos to fit this modification. 
Not applicable.
=> [Enhance] Make the parameters of get_model_complexity_info() friendly

mmengine/analysis/print_helper.py
The type of `inputs` should be one of `torch.Tensor`, `tuple[torch.Tensor, ...]` and `None`.
The type hint of arg `inputs` in `get_model_complexity_info()` should match `class FlopAnalyzer` 
https://github.com/open-mmlab/mmengine/blob/5e1ed7aaf0166f3913c84bef830456cd25c4a497/mmengine/analysis/complexity_analysis.py#L121
and `class ActivationAnalyzer`,
https://github.com/open-mmlab/mmengine/blob/5e1ed7aaf0166f3913c84bef830456cd25c4a497/mmengine/analysis/complexity_analysis.py#L192
since the argument `inputs` is finally fed into these two classes.
Otherwise, a user may be confused about what if a custom model requires more than one tensors as inputs.
Change current type hint of `inputs` in `get_model_complexity_info()` from 
```python
Optional[torch.Tensor]
```
to
```python …
```
=> [Enhance] Complement type hint of get_model_complexity_info()

mmengine/hooks/checkpoint_hook.py
Multiple checkpoints will be saved when using multiple GPUs and `published_keys` is set. This behavior is unexpected since only the main process is responsible for saving the checkpoint.
Decorating `_publish_model()` method with `master_only` decorator in `CheckpointHook`.
3. If the modification has potential influence on downstream …
=> [Fix] Fix publishing multiple checkpoints when using multiple GPUs

docs/en/migration/hook.md
Update docs: English version of migration/hook.md.
Add English version doc migration/hook.md.
=> [Docs] Translate the migration/hook.md to English

mmengine/hooks/sync_buffer_hook.py, mmengine/runner/loops.py
This PR is tring to fix the issue mentioned in #517.
Add a call to sync buffer before each validation.
=> [Fix] Call SyncBufferHook before validation in IterBasedTrainLoop

mmengine/hooks/checkpoint_hook.py, mmengine/runner/checkpoint.py, mmengine/runner/runner.py, mmengine/testing/runner_test_case.py, tests/test_hooks/test_checkpoint_hook.py, tests/test_runner/test_checkpoint.py
=> [Fix] Failed to remove the previous best checkpoints

examples/distributed_training.py, mmengine/logging/history_buffer.py, mmengine/runner/log_processor.py, tests/test_logging/test_history_buffer.py, tests/test_runner/test_log_processor.py, tests/test_runner/test_runner.py
After PR #972, `HistoryBuffer.statistics` will be called with the [custom_keys_copy](https://github.com/open-mmlab/mmengine/pull/972/files#diff-75746b50b571a33d63b68111136d0aa29ac6ac5d788aff12b02a7f329f640728R286). However, the class attributed [`HistoryBuffer._statistics_methods`](https://github.com/HAOCHENYE/mmengine/blob/d132e41a974f6f6e99ca6bdcb9eb56b7d9d2d653/mmengine/logging/history_buffer.py#L32) will not be dumped during saving the checkpoint.  It means the resumed `HistoryBuffer`s can not call the `statistic` methods …
=> [Fix] Fix the resuming error caused by HistoryBuffer

mmengine/analysis/print_helper.py, tests/test_analysis/test_print_helper.py
Previously, the arg `input_shape` of get_model_complexity_info() is used to construct only one input tensor.
https://github.com/open-mmlab/mmengine/blob/5da24ed1021c7ebd17a5d7c89999089f15a5d4cf/mmengine/analysis/print_helper.py#L707-L708
It is inconvenient if a custom model requires more than one inputs. Such as
```python
class mymodel(nn.Module):
def __init__(self) -> None:
super().__init__()
self.l1=nn.Linear(in_features=5,out_features=6)
self.l2=nn.Linear(in_features=7,out_features=6)
def forward(self, x1, x2):
out=self.l1(x1)+self.l2(x2)
return out
```
This PR add support of using `input_shape` to construct multiple input tensors.
If `inputs` is `None`, check `input_shape`. 
If `input_shape` is a tuple of int, one input tensor will be constructed as before.
If `input_shape` is a tuple …
=> [Feature] `input_shape` of `get_model_complexity_info()` for multiple tensors

mmengine/logging/message_hub.py, tests/test_hooks/test_runtime_info_hook.py, tests/test_logging/test_message_hub.py
Reslove #988
Reslove #988
2. The modification is covered by complete unit tests. If not, …
=> [Enhancement] MessageHub.get_info() supports returning a default value

mmengine/visualization/utils.py, mmengine/visualization/visualizer.py, tests/test_visualizer/test_visualizer.py
Using Matplotlib to display images can provide more interactive features such as zoom in, and zoom out, but it also causes more interactive related overhead. Therefore, if `Visualizer.show` is used to display videos frame by frame, the frame rate will be very low. For example (based on this PR):
```python
import matplotlib.pyplot as plt
import numpy as np
from mmengine.utils import Timer
from mmengine.visualization import Visualizer
if __name__ == '__main__':
visualizer = Visualizer('test')
for i in range(100):
with …
```
=> [Enhance] Enhance the efficiency of Visualizer.show

mmengine/dist/utils.py
Related to [MMCV PR](https://github.com/open-mmlab/mmcv/pull/2625)
In [dist.utils](https://github.com/open-mmlab/mmengine/blob/ff27b723dbc2f6c2846489b8b134c353f39a4ec6/mmengine/dist/utils.py#L106-L108) we set `torch.cuda.set_device(rank % num_gpus)`, while in [Runner.wrap_model](https://github.com/open-mmlab/mmengine/blob/ff27b723dbc2f6c2846489b8b134c353f39a4ec6/mmengine/runner/runner.py#L870-L874) we set `device_ids=[os.environ['LOCAL_RANK']`. These 2 values, `local_rank` and `rank % device_counts`, are the same when each node …
=> [Fix] Distributed use correct local rank

mmengine/hooks/logger_hook.py, tests/test_hooks/test_logger_hook.py, tests/test_runner/test_runner.py
No training log when the num of iterations is smaller than the default interval. [https://github.com/open-mmlab/mmengine/issues/935](Issue)
Add judgement in  function ```after_train_iter``` of class ```LoggerHook```.
If this PR introduces a new feature, it is better to list some use …
=> [Fix] No training log when the num of iterations is smaller than the default interval

mmengine/config/config.py, tests/test_config/test_config.py
Enhance the error message raised by custom import:
```bash
ImportError: Failed to import custom modules from {'imports': ['test_custom_import_module'], 'allow_failed_imports': False}, the current sys.path is: 
/home/yehaochen/anaconda3/bin
/home/yehaochen/anaconda3/lib/python39.zip
/home/yehaochen/anaconda3/lib/python3.9
/home/yehaochen/anaconda3/lib/python3.9/lib-dynload
/home/yehaochen/.local/lib/python3.9/site-packages
/home/yehaochen/anaconda3/lib/python3.9/site-packages
/home/yehaochen/codebase/mmengine
You should set …
```
=> [Enhance] Enhance error message during custom import

mmengine/hooks/logger_hook.py, mmengine/runner/log_processor.py, tests/test_runner/test_log_processor.py, tests/test_runner/test_runner.py
`Runner` will build train_loop automatically when the `epoch`, `iter`, `max_epoch` attributes are accessed. This feature cause that the `log_processor` and `LoggerHook` will trigger the building of `train_loop` during `testing` and `validating`. This PR fix this and update the unit test to make sure unnecessary loops will not be built.
If so, please describe how it …
=> [Fix] Fix build unnecessary loop during train/test/val

mmengine/analysis/print_helper.py
Resolve #1092.
In `get_model_complexity_info`, when `inputs` is `None` and model is not in cpu, generate random inputs in the device of model.
1. Pre-commit or other linting …
=> [Fix] Fix the incorrect device of inputs in get_model_complexity_info

mmengine/runner/checkpoint.py
Fix #1128, where `statde_dict._metadata` of saved checkpoints becomes empty `OrderedDict`s
modified `weights_to_cpu()` in `runner/checkpoint.py` that it stashes `_metadata` of `state_dicts` before moving weights to cpu
N/A
N/A
3. If the modification has potential influence on downstream projects, this PR should be tested with downstream …
=> [Fix] Correctly saves `_metadata` of `state_dict` when saving checkpoints

requirements/docs.txt
As the [issue](https://github.com/urllib3/urllib3/issues/2168) says, surllib3 2.0 has deprecated the support of OpenSSL<=1.1.1.
However, the environment for building the docs only has OpenSSL  v1.0.0, and an error will be raised like this:
```bash
sphinx.errors.ExtensionError: Could not import extension sphinx.builders.linkcheck (exception: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with OpenSSL 1.0.2n  7 Dec 2017. See: https://github.com/urllib3/urllib3/issues/2168)
```
According to the …
=> [Fix] Limit urllib3 version for docs building

mmengine/device/__init__.py, mmengine/device/utils.py, mmengine/optim/optimizer/builder.py
We will support full precision training on the next generation Ascend NPU, so there is no need to enable mixed precision by default.
Determine whether the current chip supports full precision training, and automatically enable mixed precision.
Not affected.
We have verified the correctness on the Ascend NPU.
=> [Enhance] Enable full precision training on Ascend NPU.

docs/en/tutorials/runner.md, docs/zh_cn/tutorials/runner.md
修复mmengine\docs\zh_cn\tutorials\runner.md文档中，漏掉逗号的代码片段。
=> [Docs] Fix a missing comma in tutorials/runner.md

mmengine/runner/runner.py
When no random seed is specified, the random seed value is recorded as None in the log
Assign self._seed to self._randomness_cfg['seed']
=> [Fix] Correctly record random seed in log

mmengine/visualization/vis_backend.py
[1156](https://github.com/open-mmlab/mmengine/issues/1156)
MLFlow Visbackend
2. The …
=> add option to log selected config only

mmengine/visualization/vis_backend.py
There is currently a bug (#1144) when running multi GPU training with MLflowVisBackend, wherein the VisBackend seemingly will try to close on multiple processes, when it can only close on one of the processes. Checking for any `self.cfg` in the `close()` method would cause the script to crash.
The check `hasattr(self, '_mlflow')` was only done for a ending the mlflow run (`self._mlflow.end_run()`). I propose to check this at the start of the `close()` method instead.
=> [Fix] Close MLflowVisBackend only if active (#1144)

mmengine/hooks/profiler_hook.py, tests/test_hooks/test_profiler_hook.py
PyTorch profiler support profiling distributed program, however, the current implementation of ProfilerHook's method is decorated by `master_only`, which limits profiler capability.
Besides, If the `scheduler` is configured for the ProfilerHook, an error will be raised like this:
```bash
RuntimeError: stack.size() INTERNAL ASSERT FAILED at "../torch/csrc/autograd/profiler_python.cpp":963, please report a bug to PyTorch. Python replay stack is empty.
```
The main reason is that `self.profile.step` will not be called if scheduler …
=> [Fix] Fix `ProfileHook` cannot profile ddp-training

mmengine/logging/logger.py, tests/test_logging/test_logger.py
[Issue](https://github.com/open-mmlab/mmengine/issues/1148)
Deprecate the int() conversion in 
[mmengine/mmengine/logging/logger.py](https://github.com/open-mmlab/mmengine/blob/4bc2fe1aaec2d7d1464b11d50f6165494f62ef18/mmengine/logging/logger.py#L379)
Line 379 in [4bc2fe1](https://github.com/open-mmlab/mmengine/commit/4bc2fe1aaec2d7d1464b11d50f6165494f62ef18)
=> [Enhancement] Handle the case for Multi-Instance GPUs when using cuda_visible_devices

docs/en/common_usage/better_optimizers.md, docs/en/index.rst, docs/en/tutorials/optim_wrapper.md, docs/zh_cn/common_usage/better_optimizers.md, docs/zh_cn/index.rst, docs/zh_cn/tutorials/optim_wrapper.md, mmengine/optim/optimizer/builder.py
=> [Feature] Support Sophia optimizers

mmengine/runner/log_processor.py, mmengine/visualization/vis_backend.py, tests/test_runner/test_log_processor.py, tests/test_visualizer/test_vis_backend.py
In this PR, add support for other original arguments of wandb.define_metric described in: https://docs.wandb.ai/ref/python/run#define_metric
(The current `WandbVisBackend` implementation supports only the case of the `summary` metric.)
Especially the `step_metric` is helpful for defining the x-axis more flexibly.
Specifying the "iter" or "epoch" as an x-axis, we can solve the issue of resumption discussed in issue #1072. I think this PR is a better solution because this does not need additional variables like `auto_step` nor`last_step` nor extra logic and uses only the wandb's feature.
Furthermore, users can specify different x-axes depending on the metrics in the same experiment. See below:
To allow the visualizers to use the `iter` as a step, I added an `iter` key in the tag of the …
=> [Feature] Add support for full wandb's define_metric arguments

mmengine/hooks/checkpoint_hook.py, mmengine/runner/runner.py, tests/test_hooks/test_checkpoint_hook.py
save checkpoint again to update the best_score and best_ckpt stored in message_hub because the checkpoint saved in `after_train_epoch` or `after_train_iter` stage only keeps the previous best checkpoint not the current best checkpoint which causes the current best checkpoint can not to be removed when resuming training.
- save checkpoint again to update best_ckpt of ckpt
- If the current checkpoint is the best checkpoint, it will be saved without the effect of interval.
For example, if interval=2 and the current epoch is 5, only …
=> [Fix] Update the best_ckpt of checkpoint if the current epoch has the best performance

mmengine/runner/runner.py
RuntimeError when attempting to resume a run. It seems the logic for triggering the runtime error is incorrect (or the error message is incorrect, but this PR is based on the assumption that the error message is correct).
Remove a `not` to fix the logic. This makes the RuntimeError trigger if `self.auto_scale_lr` has a key called "enable" and that key is `True`. This is the desired logic if we consider the error message which asks the user to set "enable" to `False` to avoid the error.
I did this in 30 seconds so admittedly I haven't followed the checklist. I'd be happy to file an issue and allow a core maintainer to carry on from here. Please let me know.
=> Refine the error message when auto_scale_lr is not set correctly

docs/en/get_started/introduction.md
"Introduction" is the entry-point for new users to MMEngine and our documentation.
However, while the Chinese documentation has an introduction, the English documentation lacks an introduction and refers readers to the Chinese docs.
This branch provides an English translation of the Chinese "Introduction" document.
This branch modifies the English `docs/en/get_started/introduction.md` by providing a translation from the Chinese version [(permalink)](https://github.com/open-mmlab/mmengine/blob/19aa1eb7800888425ce2a24d5f93b58304821821/docs/zh_cn/get_started/introduction.md).
N/A
N/A
1. ✅ Pre-commit or other linting tools are used to fix the potential lint issues.
2. ✅ The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
3. ✅ If the …
=> [Docs] English introduction

mmengine/evaluator/metric.py
`results` variable was not created when `collect_device='gpu'`, causing an error.
=> [Fix] gpu collection during evaluation

docs/en/advanced_tutorials/config.md, docs/en/api/config.rst, docs/zh_cn/advanced_tutorials/config.md, docs/zh_cn/api/config.rst, mmengine/config/__init__.py, mmengine/config/config.py, mmengine/config/utils.py, tests/data/config/lazy_module_config/error_mix_using2.py, tests/data/config/lazy_module_config/load_mmdet_config.py, tests/data/config/lazy_module_config/toy_model.py, tests/test_config/test_config.py
1. Replace 'if base' with 'with read_base'. 
2. Add ConfigParsingError
3. make Config.to_dict return string.
4. Only convert dict and OrederedDict when setitem or setattr for ConfigDict
If this PR introduces a new …
=> [Refacor] Replace 'if base' with 'with read_base' context manager

README.md, README_zh-CN.md, docs/en/api/optim.rst, docs/en/common_usage/large_model_training.md, docs/en/common_usage/save_gpu_memory.md, docs/en/index.rst, docs/zh_cn/api/optim.rst, docs/zh_cn/common_usage/large_model_training.md, docs/zh_cn/common_usage/save_gpu_memory.md, docs/zh_cn/index.rst, mmengine/optim/__init__.py
=> [Docs] how to train a large model

mmengine/config/config.py, mmengine/config/lazy.py, mmengine/config/utils.py, tests/data/config/lazy_module_config/test_mix_builtin.py, tests/test_config/test_config.py
1. Fix pickle error in config.
2. Remove unnecessary key of imported object during dumping the config
3. Enhance the logic to judge the builtin module.
If this PR introduces a new feature, it is better to list some use …
=> [Fix] Fix pickling the Python style config

mmengine/hooks/runtime_info_hook.py, tests/test_hooks/test_runtime_info_hook.py
Some numpy scalars (float32, float16, ...) are misclassified as non-scalar values inRuntimeInfoHook.
See:
```
from mmengine.hooks.runtime_info_hook import _is_scalar
v = np.mean([0.5])
print(_is_scalar(v.astype(np.float16)))  # => False
print(_is_scalar(v.astype(np.float32)))  # => False
print(_is_scalar(v.astype(np.float64)))  # => True
```
This causes problems when the custom metrics are calculated in numpy because the log_processor looks to collect only scalar values as metrics to give the visualizer them.
Added np.floating and np.integer as valid scalar types.
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep …
=> Fix scalar check in RuntimeInfoHook

README.md, README_zh-CN.md
=> [Docs] Add the data flow of Runner in README

mmengine/_strategy/__init__.py, mmengine/_strategy/deepspeed.py, mmengine/model/wrappers/_deepspeed.py, mmengine/optim/__init__.py, mmengine/optim/optimizer/__init__.py, mmengine/runner/_flexible_runner.py
If the user has not installed deepspeed and use deepspeed strategy, an implicit error of DeepSpeedStrategy not in REGISTRY will be raised.
Because of [here](https://github.com/open-mmlab/mmengine/blob/b2295a258c4af3cdeb1a55fa5e49cddbd1c6c0bf/mmengine/_strategy/__init__.py#L10C13-L10C13)
=> [Suggest] enable explicit error for deepspeed not installed

docs/en/tutorials/hook.md, docs/zh_cn/tutorials/hook.md, mmengine/_strategy/fsdp.py, mmengine/hooks/checkpoint_hook.py, mmengine/hooks/hook.py, tests/test_hooks/test_checkpoint_hook.py, tests/test_hooks/test_logger_hook.py
Add parameter save_begin to control the epoch number or iteration number at which checkpoint saving begins. As issue https://github.com/open-mmlab/mmengine/issues/1192 descriped.
If this PR introduces a new feature, it is …
=> [CodeCamp2023-472] Add parameter save_begin

mmengine/dist/utils.py
Fix the problem that multi-node distributed training would fail at initial when training with MLU.
In `mmengine/dist/util.py`, we change rank to local rank when initializing process group with MLU.
None
None
=> Support multi-node distributed training with MLU backend

mmengine/model/efficient_conv_bn_eval.py, tests/test_model/test_efficient_conv_bn_eval.py
Prior to this PR, `efficient_conv_bn_eval` operates in module level. It modifies the `forward` function of `conv` and `bn` modules. Therefore, it cannot deal with multiple usage of `conv`.
This PR improves the `efficient_conv_bn_eval` feature to operate in **computation** level. We fuse each computation of `conv` and `bn`. No changes in `state_dict`, no constraints for the network architecture. As long as there are `conv` + `bn` in `eval` computation patterns, this PR works.
See the updated test for example.
No. It just changes the implementation of `efficient_conv_bn_eval`.
=> use graph transform to deal with more general cases for efficient_conv_bn_eval

mmengine/config/config.py
Overide __reduce_ex__ to void `self.items` will be
called by CPython interpreter during pickling. See more details in
https://github.com/python/cpython/blob/8d61a71f9c81619e34d4a30b625922ebc83c561b/Objects/typeobject.c#L6196
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this …
=> [Fix] Fix `ConfigDict.items` will be called during dump

mmengine/registry/build_functions.py, mmengine/registry/registry.py, tests/test_registry/test_build_functions.py, tests/test_registry/test_registry.py
`build_from_cfg` catches all exception when building the registered object, and raise an unfriendly error. For example, an value error will be raised during building the metric, the error raise by `build_from_cfg` will like this:
```bash
Traceback (most recent call last):
File "/home/yehaochen/codebase/mmengine/mmengine/registry/build_functions.py", line 122, in build_from_cfg
obj = obj_cls(**args)  # type: ignore
File "/home/yehaochen/codebase/mmdetection/mmdet/models/dense_heads/retina_head.py", line 57, in __init__ …
```
=> [Enhance] Enhance error information in build function

mmengine/hooks/runtime_info_hook.py, mmengine/logging/message_hub.py, tests/test_hooks/test_runtime_info_hook.py, tests/test_logging/test_message_hub.py
Users might want to execute different logic in the `transform` of the pipeline (such as `RandomCrop`) based on the current stage (train, val, or test).
```python
from mmcv.transforms import BaseTransform
from …
```
=> Add the loop stage in message_hub

mmengine/visualization/visualizer.py, tests/test_visualizer/test_visualizer.py
To solve PR #1267 .
Change the logic in the constructor of Visualizer. 
If vis_backends is not None, then check whether save_dir is None. If true, and if any of vis_backends has no save_dir, give users a warning. If vis_backends is None, give users a warning.
=> [Feature] Fix Visualizer that built vis_backends will not be used when save_dir is None

docs/en/common_usage/distributed_training.md, docs/zh_cn/common_usage/distributed_training.md
=> [Docs] Introduce how to customize distributed training settings

examples/text_translation.py
One of Openmmlab codecamp task.
Added a example script training a [t5-small](https://huggingface.co/t5-small) model on [opus books, a multi-language text translation dataset](https://huggingface.co/t5-small). Default task is to translate English text to French, which is configurable from line 67 to 69, and line 92.
_No other code is altered, hence I didn't go through unit tests or add docs._
=> [CodeCamp2023-473] Add a text translation example

docs/en/api/visualization.rst, docs/en/common_usage/visualize_training_log.md, docs/zh_cn/api/visualization.rst, docs/zh_cn/common_usage/visualize_training_log.md, mmengine/visualization/__init__.py, mmengine/visualization/vis_backend.py, requirements/tests.txt, tests/test_visualizer/test_vis_backend.py
CodeCamp2023
1. Add Neptune backend to visualizer. The original task is to add segmind, however the mentor suggest to use Neptune as backend instead after searching the docs about segmind and finding that it does not suit for the task.
NO
NO
**add aditional unit test for Neptune backend test**
2. The modification is covered by complete unit tests. If not, …
=> [CodeCamp2023-Task288] Add NeptuneVisBackend

mmengine/dist/__init__.py, mmengine/dist/dist.py
1. The use of the 'set_npu_compile' function can lead to failures in launching multiprocessing on Ascend NPU. Please refer to the provided reference for more details. #1307 https://www.hiascend.com/document/detail/zh/canncommercial/63RC2/modeldevpt/ptmigr/ptmigr_0058.html
2. collect_resulst for Ascend NPU added.
add collect_resulst_npu.
```python
"""test.py"""
import os
import torch
import torch_npu
import mmengine.dist as dist
import torch.distributed as torch_dist
torch.npu.set_device(int(os.environ['LOCAL_RANK'])) …
```
=> [Feature] Add collect_results support for Ascend NPU

mmengine/_strategy/deepspeed.py
Unify the parameter format for `DeepSpeedStrategy`. Parameters such as `gradient_accumulation_steps` are able to override the input deepspeed config, while the default values for these parameters are set to None,  implying no override.
`mmengine/_strategy/deepspeed.py`
If this PR …
=> [Enhance] Unify the parameter style of DeepSpeedStrategy

mmengine/dataset/dataset_wrapper.py
Be able to check the metainfo which is one numpy ndarray. #1330
```python
if isinstance(self._metainfo[key], np.ndarray) and isinstance(
dataset.metainfo[key], np.ndarray):
if not np.array_equal(self._metainfo[key],
dataset.metainfo[key]):
raise ValueError(
f'The meta information of the {i}-th dataset does'
'not match meta information of the first dataset')
```
If so, please describe how it breaks the compatibility and how the …
=> [Fix] Fix ndarray metainfo check in ConcatDataset

docs/en/api/visualization.rst, docs/en/common_usage/visualize_training_log.md, docs/zh_cn/api/visualization.rst, docs/zh_cn/common_usage/visualize_training_log.md, mmengine/visualization/__init__.py, mmengine/visualization/vis_backend.py, requirements/tests.txt, tests/test_visualizer/test_vis_backend.py
Add `DVCLiveVisBackend`
**Note:**
The latest vesion of `dvclive` in Python 3.7 is `0.9.0` which doesn't support `log_param` and `log_params`.
Therefore, Python version should be 3.8 or higher version to use `DVCLiveVisBackend`.
=> [CodeCamp2023-287] Add `DVCLiveVisBackend`

docs/en/api/visualization.rst, docs/en/common_usage/visualize_training_log.md, docs/zh_cn/api/visualization.rst, docs/zh_cn/common_usage/visualize_training_log.md, mmengine/visualization/__init__.py, mmengine/visualization/vis_backend.py, requirements/tests.txt, tests/test_visualizer/test_vis_backend.py
Add `AimVisBackend`
resolve #1115
=> [CodeCamp2023-668] Add `AimVisBackend`

mmengine/runner/log_processor.py
When `log_with_hierarchy` is set to True, the keyword `mode` appears nested multiple times in the log. For example, val/val/data_time: 0.0332 val/val/time: 0.4490.
https://github.com/open-mmlab/mmengine/blob/a483dba9d15308f9442e87faf80c1d7279137519/mmengine/runner/log_processor.py#L379
```
for log_cfg in custom_cfg:
if not reserve_prefix:
data_src = log_cfg.pop('data_src')
log_name = f"{log_cfg.pop('log_name', data_src)}"
else:
data_src = f"{mode}/{log_cfg.pop('data_src')}"
log_name = f"{mode}/{log_cfg.pop('log_name', …
```
=> [Fix] The keyword mode appears nested multiple times in the log

docs/en/common_usage/better_optimizers.md, mmengine/optim/optimizer/builder.py, requirements/tests.txt, tests/test_optim/test_optimizer/test_optimizer.py
[bitsandbytes](https://github.com/TimDettmers/bitsandbytes) provides `AdamW8bit`, `Adam8bit`, `Adagrad8bit`, `PagedAdam8bit`, `PagedAdamW8bit`, `LAMB8bit`, `LARS8bit`, `RMSprop8bit`, `Lion8bit`, `PagedLion8bit` and `SGD8bit` optimziers。
```
pip install bitsandbytes
```
```
optim_wrapper=dict(optimizer=dict(type='AdamW8bit', lr=1e-4, weight_decay=1e-2))
```
=> [Feature] Support bitsandbytes

mmengine/utils/misc.py, tests/test_utils/test_misc.py
=> [Fix] Fix get class attribute from a string

docs/en/common_usage/better_optimizers.md, mmengine/optim/optimizer/builder.py, requirements/tests.txt, tests/test_optim/test_optimizer/test_optimizer.py
[transformers](https://github.com/huggingface/transformers) provides `Adafactor` optimizer.
It is often used when training Stable Diffusion XL.
```
pip install transformers
```
```
optim_wrapper = dict(
optimizer=dict(
type='Adafactor',
lr=1e-5,
weight_decay=1e-2,
scale_parameter=False,
relative_step=False))
```
=> [Feature] Support Adafactor Optimizer

mmengine/config/config.py
yapf v0.40.2 has removed `verify` from `FormatCode`.
https://github.com/google/yapf/commit/6bc6de17f4da1e8fd04aad36b02b1252076387ef
[Please describe the motivation of this PR and the goal you want to achieve through this PR.](https://github.com/google/yapf/releases/tag/v0.40.2)
=> [Bugfix] Delete yapf verify

mmengine/runner/runner.py
When I followed the 15-minute tutorial in MMENGINE to write the configuration file, I found that I was missing the setting of env_cfg, but directly instantiating the Runner does not require setting env_cfg. Ensuring that the default parameters for a runner instantiated from a configuration file and instantiated directly are the same will be less confusing.
Add default parameters consistent with the Runner class to the env_cfg of the configuration file.
=> [Fix] Ensure from_cfg of Runner have the same defaults values as its __init__

mmengine/dataset/base_dataset.py, tests/test_dataset/test_base_dataset.py
Allowing metainfo to be more generic, so that it is compatible with other dict-like config systems.
Allowing metainfo to be `Mapping` (more generic), instead of just `dict`.
No
If so, please describe how it breaks the compatibility and how the downstream projects should modify …
=> [Enhance] metainfo of dataset can be a generic dict-like Mapping

mmengine/_strategy/fsdp.py, mmengine/model/wrappers/fully_sharded_distributed.py
Support using gradient checkpointing in FSDP https://github.com/open-mmlab/mmdetection/pull/10981
If so, please describe how it breaks the compatibility and …
=> [Feature] Support using gradient checkpointing in FSDP

mmengine/dist/utils.py
To support slurm distributed training for mlu devices.
Modify the _init_dist_slurm function in `mmengine/dist/utils.py` to support slurm distributed training for mlu devices.
If so, please describe how it breaks the …
=> [Feature] Support slurm distributed training for mlu devices

mmengine/optim/optimizer/builder.py
In [`register_bitsandbytes_optimizers`](https://github.com/open-mmlab/mmengine/blob/6c5eebb823e3c9381d63fd0cd1873ed1bd9ee9de/mmengine/optim/optimizer/builder.py#L132C14-L154), some optimizer modules are missing from a low version of `bitsandbytes`, resulting in a bug for users with lower versions. (e.g. …
=> [Fix] fix a bug when module is missing in low version of bitsandbytes

mmengine/_strategy/deepspeed.py
Support `exclude_frozen_parameters` for `DeepSpeedStrategy`'s `resume`.
In https://github.com/open-mmlab/mmengine/pull/1415, `exclude_frozen_parameters` has been added to `save_checkpoint` and `load_checkpoint`, while `resume` was overlooked...
`mmengine/_strategy/deepspeed.py`
Does the modification introduce changes …
=> [Fix] Support `exclude_frozen_parameters` for `DeepSpeedStrategy`'s `resume`

mmengine/_strategy/base.py
Fix the bug in the `load_model_state_dict()` function in `BaseStrategy`. The bug is caused by incorrect argument assignments.
Specifically, the variable `revise_keys` in `load_model_state_dict()`:
https://github.com/open-mmlab/mmengine/blob/85c0976bc2434157f786d44cdd8f0fb2955414f0/mmengine/_strategy/base.py#L802
is passed into the `logger` argument in `_load_checkpoint_to_model()`:
https://github.com/open-mmlab/mmengine/blob/85c0976bc2434157f786d44cdd8f0fb2955414f0/mmengine/runner/checkpoint.py#L585-L592
Use key-value assignment for `strict` and `revise_keys`.
3. If the modification has potential …
=> [Fix] fix bug in `load_model_state_dict` of `BaseStrategy`

mmengine/dist/utils.py
Fix the problem that multi-node distributed training would fail at initial when training with NPU.
In mmengine/dist/util.py, we change rank to local rank when initializing process group with NPU.
None
None
2. The modification is covered by …
=> [Fix] Support multi-node distributed training with NPU backend

docs/en/common_usage/distributed_training.md, docs/zh_cn/common_usage/distributed_training.md
=> fix nnodes in the doc of ddp training.

mmengine/runner/loops.py
`IterBasedTrainLoop` is not correct for resume. The beginning data index is 0, instead of `self._iter`
If so, please describe how it breaks the compatibility …
=> [Fix] Fix the resume of iteration

mmengine/device/__init__.py, mmengine/device/utils.py, mmengine/dist/dist.py, mmengine/dist/utils.py, mmengine/hooks/empty_cache_hook.py, mmengine/logging/logger.py, mmengine/model/base_model/base_model.py, mmengine/model/base_model/data_preprocessor.py, mmengine/optim/optimizer/amp_optimizer_wrapper.py, mmengine/runner/amp.py, mmengine/runner/log_processor.py, mmengine/runner/utils.py, mmengine/structures/base_data_element.py, mmengine/structures/instance_data.py, mmengine/utils/dl_utils/collect_env.py, mmengine/utils/dl_utils/time_counter.py, tests/test_device/test_device.py, tests/test_dist/test_dist.py, tests/test_hooks/test_ema_hook.py, tests/test_hooks/test_empty_cache_hook.py, tests/test_runner/test_amp.py, tests/test_runner/test_log_processor.py
=> [Feature] Add the support for musa device support

mmengine/_strategy/deepspeed.py
`self.model.save_checkpoint` saves much more files, including model weights, optimizer states.
1. By passing `save_optimizer=False` to `default_hooks.CheckpointHook`, we can only save weights of DeepSpeed model.
```diff
default_hooks = dict(
timer=dict(type=IterTimerHook),
logger=dict(type=LoggerHook, interval=10), …
```
=> [Feature] Support `save_optimizer=False` for DeepSpeed

tests/test_utils/test_dl_utils/test_torch_ops.py
Due to the upgrade of `pytest`, passing None (`with pytest.warns(None) as record:`) has been deprecated.
According to https://docs.pytest.org/en/latest/how-to/capture-warnings.html#additional-use-cases-of-warnings-in-tests
Does the modification introduce changes that break the backward-compatibility of the downstream …
=> [Fix] Fix warning capture

mmengine/visualization/vis_backend.py, tests/test_visualizer/test_vis_backend.py
https://mlflow.org/docs/latest/python_api/mlflow.html?highlight=create_experiment#mlflow.create_experiment
=> [Feature] Support custom `artifact_location` in MLflowVisBackend.

README.md, README_zh-CN.md
=> Add the supported pytorch versions in README

mmengine/_strategy/deepspeed.py, mmengine/optim/optimizer/default_constructor.py, tests/test_optim/test_optimizer/test_optimizer.py
It will cause errors when initializing DeepSpeed optimizer, with
1. Freezing some parameters of the model
2. Setting `paramwise_cfg` for optimizer to set different lr or weight_decay for different parameters
This is because that if setting `paramwise_cfg`, mmengine will treat each parameter (including frozen parameters) …
=> [Fix] Delete frozen parameters when using `paramwise_cfg`

mmengine/model/base_model/base_model.py, mmengine/runner/loops.py
Since early stopping requires validation loss as a possible metric, mmengine currently does not support calculating and parsing validation loss as a metric.
However, due to the inconsistency of model implementations and the fact that calculating validation loss is not a common requirement, the process of calculating validation loss should not be initiated by mmengine, but rather, initiated by the model and returned by mmengine with a convention to be parsed and returned as a metric. 
Thus this PR aims to implement this return-and-resolve convention without introducing breaking change.
In order not to introduce breaking change, we chose to return the loss computed by the model at `val_step` (`model.forward` with `mode='predict'` or `predict`) wrapped by `BaseDataElement` and append after …
=> [Feature] Support calculating loss during validation

mmengine/testing/_internal/distributed.py
fix error when pytest>=8.2
https://github.com/pytorch/pytorch/pull/127512
2. The modification is covered by complete unit tests. If not, please add …
=> fix error when pytest>=8.2

mmengine/optim/optimizer/builder.py, mmengine/registry/build_functions.py, mmengine/registry/root.py, mmengine/testing/_internal/distributed.py
The Adafactor optimizer in PyTorch 2.5 is not working correctly.
Added hardcode to rename PyTorch's Adafactor optimizer to torch_Adafactor and added a warning for users using Adafactor.
Compatible with PyTorch and versions below 2.4.
If this PR introduces a new feature, it is better to list some use cases here, and …
=> fix Adafactor optim on torch2.5 and fix compatibility

mmengine/config/config.py
`import yapf` could raise unexpected error like this:
Just move the import logic in function to avoid this error if config is not used
2. The modification is covered by complete unit tests. If not, please …
=> [Enhance] Move `import yapf` to function

mmengine/optim/optimizer/builder.py
- Add try-except blocks around optimizer registration to gracefully handle import failures
- Extend ImportError handling to include RuntimeError for CUDA-related issues
- Add warnings.warn to notify users of failed optimizer imports without breaking execution
Please describe the motivation of this PR and the goal you …
=> [Enhance] Suppress import errors for optional optimizers
